apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authelia-db-backup-credentials
    namespace: authelia
spec:
    secretTemplates:
        - name: authelia-db-backup-credentials
          stringData:
            ACCESS_KEY_ID: ENC[AES256_GCM,data:/p0CqLtamlW/7kW6N6QOgqSL9n2NHcD5J/o=,iv:FoxQyc+HZWdjooi5dISJKlB5+lzp8xnv6a7PNcCv2Eg=,tag:96ezNSiQgRFsAPQ85xyZHQ==,type:str]
            ACCESS_SECRET_KEY: ENC[AES256_GCM,data:rEq8MbFZ9eO9oVgEH86J9nM6TU3Ilb34MDsckhapLJNvN3zNplyYXBIISP9NeDFjE3Oegrcvf8Yy5ucBMxFlew==,iv:xw9b1FX4Nd4N2gDE5Poqt6dbtH2VU5waLWoXL3DVtHU=,tag:WCLloXoSrox3T2bcNiQJPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VTVYdmlwWTI1akdJK0pG
            eENaYTFFQlUxamVJdXVoRWppTlUwTHZTQzJJCjkrQjZBTGRjUGMyYzNIY1FTdlR3
            TWlmaHhDUXZhVFIrcVJZWHVvVEVUMUUKLS0tIFIyYmsrYU5JYTVoenpDeHdzdnZr
            UjNXNHRoUnU1UklZVUVzZnB2T0Y4VUkKz8VKSzaSCV9xnw/BcKDdSgYkkA55zKlY
            zPKQaGGX+mVlBEk3/PZ1DpyvJ0F4YKQzpMtk5pVjZXnEpwWtdwPxVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T15:47:45Z"
    mac: ENC[AES256_GCM,data:auojq/Dla70gh3NXDf9WplTzp2PRbqm7svaVK+E5SsLppVxktsT8j+Nvgw9mV6DdjBAb/Kd+6w0RLN1q5u+/ZQuiUlbOPn36lhmSjj4Vop9A+f3VS8vLqqG0Q9HWC8BViBg/x2uZLcqs4kaWlEGznirRsvx8U/w+tBAuKJwuXAc=,iv:5sLBVFXSDxvOfh/MowNpbL3t+rKUIcyccNjRiIUETGc=,tag:qdUF5LG3cfB11XrDu3XNuQ==,type:str]
    version: 3.13.1
