apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-db
  namespace: authelia
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  bootstrap:
    initdb:
      database: authelia
      owner: authelia
      secret:
        name: authelia-db-credentials

  storage:
    size: 5Gi
    storageClass: nfs-db
