apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authelia-secrets
    namespace: authelia
spec:
    secretTemplates:
        - name: authelia-secrets
          stringData:
            JWT_SECRET: ENC[AES256_GCM,data:3t4uSoTnNluzqKJUR+/bZBnKneLS1ZekmBN+crfWuV3N69Txx8PIXZNz0kb63NhxB5AJ1RSPJjkdQ6+UKFBPbQ==,iv:XnQiFWtJdrEGTMLI1PcNaQvM4ubkVO91IGmMMNAfh14=,tag:wutAYAXdIQR2ZJfl9V8iaA==,type:str]
            SESSION_SECRET: ENC[AES256_GCM,data:P3oTIIe59CUSmM3vYdjpWx4Gkhj+VND+/51U+Fyt/Ivu+nBm1UjdB7eTURjxmmloDmOMDp+HYag69DrluJeFXQ==,iv:xI5zXKUQygB1pALfBT9nbTartWojyXkzOrq8IGWBjlk=,tag:c1gwM7ONC0Tk4W+OQzsTwg==,type:str]
            STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:YznC4nBRnzZEJwruHcK4JjA21mS20dS8wg8tuzcjE77L34SsxQg+AXOfgXpcTPKVaI1ClsanunzQbIju+pfH7g==,iv:Pf+ghOrnDg0OEhktDBzJYSj7TpNjrHT2vvTZfmWOaeE=,tag:sTz4IdnYQKAxGJM3Hwkfiw==,type:str]
        - name: authelia-db-credentials
          stringData:
            username: ENC[AES256_GCM,data:Hyt0KnegzDI=,iv:YCKd0n0aZcwA740rdPQ0peqcfcW234mP8yVsupuUC8Q=,tag:+yW++wybpthbOIid4UX/lA==,type:str]
            password: ENC[AES256_GCM,data:KsB/nMevq8AtZ5J57I3LSyVE0SEB9QJ9kKurvHRejyoX+LHrQSlRLHI9pgK3cjpN0OhW2msPu/sQw1riuPfRkv5imeqzFfyMwzzXQb8I5V1dm1yEaTM79s/k7S6xTkMR2w==,iv:kOKvRnTqmKqm+rpPmgd8UBRvPPAmjmnuCaQJ5nV9xDQ=,tag:+tHk3sYznRpx97TGxvmxmg==,type:str]
        - name: dragonfly-secret
          stringData:
            password: ENC[AES256_GCM,data:0jJJZDP7owbZqLAb7GBv,iv:HCumrYFQbVmXv4mGX2M/FjDluQ3U3Zb9FsJhmVx8psI=,tag:8e7sJn/TLtBhbhH7+rZWyw==,type:str]
        - name: authelia-users
          stringData:
            users.yaml: ENC[AES256_GCM,data:Bm0GTc0ZqXG2wP96SQJ2e/PajMf/b6UP+r8HmocPhY/7AJDr5EG4qYRNuhUNsGHvgi3KxxVXJTeQKDPi8JetgNFdUPye3Jsl3iyDeDxzULuZrPjsInznQwvQ6kA0dDZIKPf/Qan9Fxl48VgZwmzC6SZMIdV+e8WnLp5wleEbO+iygfuKJcLZ9oMltGZwCegWBxmJvFeToYPT0WTUXhLKj+WVmvr6wdTJON8iV2YgRnXjtq0hbm+8I58b6c63+BurxjU0KYzNKWDDxj3S0pBmFnqHSZQEuQh0e5vyl9omoyfg1YbCvL94ox3Y1yY6GdqBRWZPh0jqucjjKXouH6fG07O+mj0=,iv:RsfrUhQX/edKP9DEH4xig6Ctpiuf7aHfI3UaT+vBtrc=,tag:aQk1CQJACQP74z2wP4hemA==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWGtpZjFHSzZ1QUI5K0RX
            ZmtXZWxnUkJvTnpTM210Q0lMYjlTTUkyK1Q0ClI3L2E0RU05czZibXhrcnZRYThm
            MytDaTEzckM2bkRKSGlvbnBMR2ZjVXMKLS0tIE1QOEY2YUJ6bkk4QjVoc1hIc05W
            L01BYmtKL21zeCtuclczY2R1YUg5TWcKcFd3yVuVCY7L6K2RnPj4uQK0XOmaWExq
            OSroEJDKjqNVbfKz4bUA65SbraVbKELyOZUkhYn9ZTWB0DGDLJ9Wyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T16:46:01Z"
    mac: ENC[AES256_GCM,data:j2H2mqT+KrJMJMaVFH352za7NMmlqKOL/dOUJUy3/6HIWg0Q8gR/xHvlgSoHbwVj6pzSe4PofwI6aclOFb7p8/qdTRhP/8TChrk0pl+6eOXIbprybbLxBQ1/ITfEqspvaJcSU+ZkbmAYqulwr6GsL/va3yVkNoJyjvBzUMpnWHY=,iv:JjtzrW0ac2jq2pP1fMo8PMDzzmJnd4A0LMCl/I3mzl4=,tag:KFWqgwC9ePtr3QBhIjA1Tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
