apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authelia-secrets
    namespace: authelia
spec:
    secretTemplates:
        - name: authelia-secrets
          stringData:
            JWT_SECRET: ENC[AES256_GCM,data:3t4uSoTnNluzqKJUR+/bZBnKneLS1ZekmBN+crfWuV3N69Txx8PIXZNz0kb63NhxB5AJ1RSPJjkdQ6+UKFBPbQ==,iv:XnQiFWtJdrEGTMLI1PcNaQvM4ubkVO91IGmMMNAfh14=,tag:wutAYAXdIQR2ZJfl9V8iaA==,type:str]
            SESSION_SECRET: ENC[AES256_GCM,data:P3oTIIe59CUSmM3vYdjpWx4Gkhj+VND+/51U+Fyt/Ivu+nBm1UjdB7eTURjxmmloDmOMDp+HYag69DrluJeFXQ==,iv:xI5zXKUQygB1pALfBT9nbTartWojyXkzOrq8IGWBjlk=,tag:c1gwM7ONC0Tk4W+OQzsTwg==,type:str]
            STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:YznC4nBRnzZEJwruHcK4JjA21mS20dS8wg8tuzcjE77L34SsxQg+AXOfgXpcTPKVaI1ClsanunzQbIju+pfH7g==,iv:Pf+ghOrnDg0OEhktDBzJYSj7TpNjrHT2vvTZfmWOaeE=,tag:sTz4IdnYQKAxGJM3Hwkfiw==,type:str]
            SMTP_PASSWORD: ENC[AES256_GCM,data:18MepeaF+cpUJnklpoTeBQ==,iv:h463Z9GYLd3+2LUp5CtZ0kCfGWqo14iiQdRwN/jZ5+E=,tag:j62zrHeHoasfWsf+QXq5QQ==,type:str]
        - name: authelia-db-credentials
          stringData:
            username: ENC[AES256_GCM,data:Hyt0KnegzDI=,iv:YCKd0n0aZcwA740rdPQ0peqcfcW234mP8yVsupuUC8Q=,tag:+yW++wybpthbOIid4UX/lA==,type:str]
            password: ENC[AES256_GCM,data:KsB/nMevq8AtZ5J57I3LSyVE0SEB9QJ9kKurvHRejyoX+LHrQSlRLHI9pgK3cjpN0OhW2msPu/sQw1riuPfRkv5imeqzFfyMwzzXQb8I5V1dm1yEaTM79s/k7S6xTkMR2w==,iv:kOKvRnTqmKqm+rpPmgd8UBRvPPAmjmnuCaQJ5nV9xDQ=,tag:+tHk3sYznRpx97TGxvmxmg==,type:str]
        - name: dragonfly-secret
          stringData:
            password: ENC[AES256_GCM,data:0jJJZDP7owbZqLAb7GBv,iv:HCumrYFQbVmXv4mGX2M/FjDluQ3U3Zb9FsJhmVx8psI=,tag:8e7sJn/TLtBhbhH7+rZWyw==,type:str]
        - name: authelia-users
          stringData:
            users.yaml: ENC[AES256_GCM,data:mSyu1L+jwN6NHizv38EO0+TCRIkfgDTZi9KoC8ZL32nsx1gkyvodWZiEStB1RXosRMJgZc+RBZjtIU0z2N9Y3Mmap88F1InEr02aKOcF5azDUEz7v6OXqCiTG+0PSUo9zYJBiLU1IyMYNgZZpTCL/bk8B1v68qp84TiiUHc2EAa38ucPsSQtbc/bk/K0IF3cdI/D2K34VrOBE9SrtqX1FTncFXHrtCV0AthISYbPf1tOtwpg4gzMN+3mO4V641srNqSxVusaCSFIBu0XvI9PLpK+RJ6k/f8NVeEiHRfaT/vE1JrSjxEmOwUZHpzKc6ST803jhT7FomYfTsXs2+CFhb9ip+U=,iv:9NVzXBQ285kyK4oJIKxvyhFs213DZ+BBW2fs0l4UJK4=,tag:uKDHO7BoCjuhyni+YUPpRg==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWGtpZjFHSzZ1QUI5K0RX
            ZmtXZWxnUkJvTnpTM210Q0lMYjlTTUkyK1Q0ClI3L2E0RU05czZibXhrcnZRYThm
            MytDaTEzckM2bkRKSGlvbnBMR2ZjVXMKLS0tIE1QOEY2YUJ6bkk4QjVoc1hIc05W
            L01BYmtKL21zeCtuclczY2R1YUg5TWcKcFd3yVuVCY7L6K2RnPj4uQK0XOmaWExq
            OSroEJDKjqNVbfKz4bUA65SbraVbKELyOZUkhYn9ZTWB0DGDLJ9Wyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-29T08:03:27Z"
    mac: ENC[AES256_GCM,data:c8brO1KBgoV125qTlmiMJAGnJLDeLk+9AdDfKkSaHDy5FrY14L45RZcQrq2iF8ehO0MoJbrkAlH35XawLCTydqcQ1OlTNUQ/H1sd2JgQGlGaOIP6L4hjO13OeFmKd6qMIaRhW72Ik7GZ/NHbhe10CfJdNhYClX02cuMO/2zRJYc=,iv:MlM3OaoMCWynehB001L3UHrPomPRC5nRZt8MyR0wUIU=,tag:UPF1Jhl6ymZiGGBPfdFhPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
