apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-secrets
    namespace: homepage
spec:
    secretTemplates:
        - name: homepage-secrets
          stringData:
            HOMEPAGE_VAR_OPENWEATHERMAP_KEY: ENC[AES256_GCM,data:EsBBAm5DD2q1B0mnbdcVTsi4EhiwALctMOpV4NCrggk=,iv:x4c9Gask+e1bHigR1EDaDFGhh4gm/yCV+RURlOqZTnc=,tag:TSwC14TT9VwcJfawfV18HQ==,type:str]
            HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:f6wKBoojwRDhSTakXBykYwtEAzj12sVF6Q==,iv://mKxrcLIWDv4dx6hG0SBnZvjzvhHSPfDEhIHeBgiho=,tag:wqBcI29t2HSVXLOhc8Zfvw==,type:str]
            HOMEPAGE_VAR_PROXMOX_PASS: ENC[AES256_GCM,data:WcuAtb7LEP8HjGx/wK/gtW+S+uv3PJrZ5Tm94eX2YHwv9zJ9,iv:ikXzwpj8UgR5XNCku6UK6xEiwLtpkB4wn6X1ZZJRz2g=,tag:tSBe2H5MqVoQTMZKAgSw+g==,type:str]
            HOMEPAGE_VAR_OPNSENSE_USER: ENC[AES256_GCM,data:qjMG1Vos8PE77lINuXc+N2/bR/KXDMMET1mxl2R6P/5mRy8nqCMQbdJrlyZXCDGyp4zPopS/oHqkGhLzsnEu2JCcXhRuIILDnoUBSif03ns=,iv:XjZ1SxVt/SNA8ewx3urXHeiqp8dSJUrTCUD/wI1uyJs=,tag:mMl34OHodd3iF4NktQEjaA==,type:str]
            HOMEPAGE_VAR_OPNSENSE_PASS: ENC[AES256_GCM,data:CKlM2+5Em/EA/zhUo0YoFl4DDK1WPB5T6u3CJA3NJqDRyXcHZnzzRDL9q8ZnHNZZJl6Auu1/1abkyovWi561bA6BGTHvlh30kFA6v9qZxSg=,iv:HpEBqZyXSCUZc7vRl7MlnNmydlgSncV7b7Bhk6ZLS5U=,tag:CG3+x0FWhr4M1jVmFCwAeQ==,type:str]
            HOMEPAGE_VAR_AUTHENTIK_KEY: ENC[AES256_GCM,data:Btu7/8rt2mjdCVhqeWIEPMRUPH31eO9mKcHqsjdeBhw5GKkS9hhmVpfAy7FNBIlDleaYui1Jwici0Edb,iv:533FE+mmCFxjpxnQHCWGQyy1gxZ78V9NNHnVg/04VmA=,tag:3sz0Z9GXtOJtsmVIT9RqwQ==,type:str]
            HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:xCFZ2nAUYCo=,iv:A/oUQ0vuRUgE2M+y8AJBGGHAIxEgVQoxAdO783v3scM=,tag:pAs5sgNXtxso/H0QzPVLOA==,type:str]
            HOMEPAGE_VAR_GRAFANA_PASS: ENC[AES256_GCM,data:AKseaGTSmrKx,iv:AjsgM/QPTPZ3o8GiHDOQoPu6GVEd109ignlIuAwujOs=,tag:O5oR/UjxdO+nBo7Fgr1tww==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WHpXUWs0c21PQjdKU3Iy
            bE41MVdFM2EvOXVvWjZoS1pOVHhxUThHdmxzClV1WXU0a1pUVUFRVktrMHI1SVUw
            MHVKeUQ3Rmh1Z1ZPdzJPbVBJcCsrNHMKLS0tIFRIVmJsSU1zYm5oNk9pbjFZaDFi
            ZStqQ3JoZWRtOGMxOHBvcUU4Y3lqbFUKo+AbeWuTL8nu5GUalk5PcdXK4muevGt+
            fro8vEent3QIjX6ZflbkwG+wc/pLliobkUhQ2ZngYQU5uAxkwNuDfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T11:20:30Z"
    mac: ENC[AES256_GCM,data:vri877yWKtKZ/VW8T/EIAJGu2DwMQ1Cb+ehtZuGKYLBpxt9AS6i0CbXnhwX4ftQeJMSkqjs0P44F+y23RbDaBvvKOIemLXXMl1wIZSkj33bVMPMtmHix+ExnkuRgs2qso3TttJzBl0beChGXjLTbAAcjbZoTSvVEPbOsfgpUnRo=,iv:ssrpfbPUAI5aFk/DP9S567ZPz/bODeRpVl23xJ8UADw=,tag:8gRZpDKSp/ym3HEeZ9k4JA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
