apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-secrets
    namespace: homepage
spec:
    secretTemplates:
        - name: homepage-secrets
          stringData:
            HOMEPAGE_VAR_OPENWEATHERMAP_KEY: ENC[AES256_GCM,data:EjUWGA5V5GzGSfb5ZalLF6P4dJiq25YWlygp5THZeu0=,iv:710bZXMYnAX2euN35wvs5hwspUONhb6WWib7HhBEBmA=,tag:cejDUt43wKJl7MRwbLf5JA==,type:str]
            HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:zgtxhKScfwhZ9jnKX91izGfU8kWit0JFMw==,iv:cHqYsuxBIbTrspcvAzA1A9EamUx9Athn9ns20DdyIeQ=,tag:Kk4gWymA5QL++ROfWyGnhw==,type:str]
            HOMEPAGE_VAR_PROXMOX_PASS: ENC[AES256_GCM,data:kEWVqL7XG92jUAIWZ85Wd9uqCTQg72rmNgvZTdfQx+vHwMA9,iv:Lr2KJ5rpSG95oPvM8E2VTnNSX0N6jYSwv83HWQSSiuQ=,tag:WzHYzW4XtcY3xrK+dJGBUw==,type:str]
            HOMEPAGE_VAR_OPNSENSE_USER: ENC[AES256_GCM,data:C+oDfwOXJ9d9uwGR86pWGVQ7F7s2DZ9081w01jIgHN4f9jqehHe9sY5NqYadEQouXD8M+WOcKyPYNlLgLtkW5/YKVYp9xY+BVYcz5q3riSM=,iv:1dx2IPeKFFuBe9GGW6y2UAC2O1PqpwzSBWrGZ9OXvK0=,tag:68nYvPfuOafWoP2ld1qFJQ==,type:str]
            HOMEPAGE_VAR_OPNSENSE_PASS: ENC[AES256_GCM,data:z1GniK11ZlxsH2CNlso5KzxFid+gXdLf3Js90VyMkACK5XUvgbKckhLm2LwgsDIn5peRpp5fWXOIbfGN1/SkADZC1pcCe7dW3+tvrnkY0Co=,iv:AIyUOfilKmAgFlIRNdOZkKnvA0EPyesAmSOpyPQMxuE=,tag:hn0hanVG/9v+SLhfKlVgXg==,type:str]
            HOMEPAGE_VAR_AUTHENTIK_KEY: ENC[AES256_GCM,data:c1Z7oy7Y6luRBX3SJfFxqXB7fgm7VvoCchEL72jrEBF6f7zff0y7kSer62UAWTqzo6zBl0FBE6/ZdKUN,iv:qh0EOJX1/4VfML6U0piojGKgP7cARjn4NDqNwJrOBII=,tag:DX5ol4bacvdvnl5og9wWng==,type:str]
            HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:b5su+a0ybrY=,iv:IkmcLngelAvFGzMFIBG5eE1Xqub0vCv3w8Av+5C1gjk=,tag:PYyb4Mbn9anT7l5BigW4Hw==,type:str]
            HOMEPAGE_VAR_GRAFANA_PASS: ENC[AES256_GCM,data:P4+yAJlROKeR,iv:Nx6RzJl6Jst2himAQDGVqOWtMS624ydqCW0EcFyyB7U=,tag:T1mcGbVL4f45S6khiWeDpg==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQWVKMENzUFNkMVZtTmgv
            Wk9ZYzJBV1JJWUdHV3lqdlNYVy9IM25nYjJVCndMMDJVaTdUUW9tYnB6Sy9IOUpT
            ME9FVHRQNmFxQldrK3ZjbEdoK1NJUjAKLS0tIGJKajNpalBnZ01ZTG56M3RKNEVm
            TXVRM3UvRXdldHdDdHUyQUp5OVRQQVUKp2/xqvAuFPKizMadlyPEEi7rFNNuHV4I
            R0kRxFcE8xivdJR/jzimtJGZMI9ddXYETqFcu9/PdMvcaYCvtLCNmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T09:52:32Z"
    mac: ENC[AES256_GCM,data:8lphfGjT1a5FASVexIsXFM6jzRHsq+94Ts8mlAUdNs5Kn8/+OED/pWE910lwJ90j+6wPi5NeT5qrb7oGvNzG/ExJBsix3g+vLRzK4l5beMpV+i/bh39WWySf/HEJOHlnzvTTUGOn2QsAN65dDfH/VXqdEuVxZHObCl8Hy8USXQo=,iv:3sOn6fEhAvPkiQKFRW+jFFYCtStmEa/58YNYZUfe4Q0=,tag:Azf8K1uyiBk/Okir4JkqpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
