apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-secrets
    namespace: homepage
spec:
    secretTemplates:
        - name: homepage-secrets
          stringData:
            HOMEPAGE_VAR_OPENWEATHERMAP_KEY: ENC[AES256_GCM,data:vMZkHfj5h0wC0GZ5MzEletjndR62VJf3xvNvOakIWOQ=,iv:QltbAnusnevmwHTC3rYnHLv6+eXeY7i3Sqlr5MHfLe8=,tag:joad6WVHa7k4fGJyi8EZ8w==,type:str]
            HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:KTs0gVxEkAjpLbhaL0YOvUJFZfQyF3yloQ==,iv:qBewiiYIdks/3QL4XS3QfUA6RxcH6pulKSBb+Hor1Kc=,tag:e8h9Dk5FRbLC4+ORMqlOUg==,type:str]
            HOMEPAGE_VAR_PROXMOX_PASS: ENC[AES256_GCM,data:LX52JHxXotaC4ycznDIAlyUNzZYpawwAKHyc1nKx276Tq1+X,iv:yTCJKQ9+hsxcvc34jcacP8vuROih4cqFI3j97oVSfAk=,tag:+RLWKfDMc1430tI8blGIpA==,type:str]
            HOMEPAGE_VAR_OPNSENSE_USER: ENC[AES256_GCM,data:E2VT2zkmgwBSP0ntnH69eDbLdHizYIAdy5U0Ud+hA+lybHi0Lk4Fl3U3gKeXbiQqMuzC6OujdHwWz4LsFyvSyWXkDcXsSPz2ehyWDi/rjOs=,iv:tVeK/IrNcknFGMnIeKmysBZRX4nkZKIJ664tvp05Zg4=,tag:oL6zy1/P62nNxGcnkiqF+A==,type:str]
            HOMEPAGE_VAR_OPNSENSE_PASS: ENC[AES256_GCM,data:IinFCNQGxaU2Ds42H/jnPWDvQa5o3kXdu+HHS5ot1G5sLHLlcEnKdgRIoGX8cid+uwERHGyIvvNrOSELxZCww0DVjCVIxiPX35KcGdnQC/g=,iv:BSRyeAT0VLTfnDQth/3lg1e1t/MG3Okt8Kr8+qd8Ps0=,tag:AZ5qwy2VOzke6/7fhbmGQg==,type:str]
            HOMEPAGE_VAR_AUTHENTIK_KEY: ENC[AES256_GCM,data:CZb2zwKk+ydzwk4PdF9R3wSWkGJxLmBr/fK+nTDw7QZIpykApDR2aXZChtcVzzAhCB7DypscfyMFawim,iv:e5/UM0tiQ6RioxCD03FQjBH88uGZ14vXUvTn/EhsaiU=,tag:ErVEtuTZOUp+0d6oDvK9PQ==,type:str]
            HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:B21yqIZSSl0=,iv:aco5tKpLkxGhdBtu+b4BQsffLVgvwKGTeeKfCG/xd5M=,tag:QIBUw5T3kbQDf92LmvQ5MA==,type:str]
            HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:f6j8uAmF2Ko7z3H2LzDBtFNeQ0Y=,iv:5IvdiLR2C9b45FEkajJz7qlZDbXH0mGZucjfWdXvXdo=,tag:5IJiqo20VacuQx78IyeOjA==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOXYvaitmNnBPdFlKN0NK
            akVGcjJPTUtoaWFSc1h3aFBKMW1VNnRnLzFnCmhqekI1N2pvdmJ0ZnF1MzFLdXZ1
            bVNKNys4L01sQTQySVRjUG5SblJrYWcKLS0tIEV0M0k4bkFZanFOVXF6QXdSZkFr
            Umg2b3FvVXNHM2hmemxyR2h3eG8wTHcKBZnfYIhQVHDIsY8weyTulZYuIH4R8OJt
            XsJxO/QaovD9+jJsCSmKPXuVjtzkmHcMQm4rNc1myhkaKZwrt7Kijg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T17:08:56Z"
    mac: ENC[AES256_GCM,data:q+9CjfHWJJ8DfKieIkRuhudviHYS/RRHOwdglzvyUSiVM3gVy4OmMPcfe535Mywv60Qcn9Hp3qmmbNbNijvFoeRi3KdYPNzO1ROVv6zPLb1Afgk2MRusifiTDvcnOiwRjO9MKykPWVoz0IdX2v+VH/BDvTsfU0LT+0fNSvz7Nkc=,iv:8ax3llqJi1eQ32ii5FMGASWLVuu7R9zgA+EuP3Thu4Y=,tag:YZ45k/94C8TlD7KW3DNvgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
