apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: affine-secrets
    namespace: affine
spec:
    secretTemplates:
        - name: affine-db-credentials
          stringData:
            username: ENC[AES256_GCM,data:z3r5+QpX,iv:PxFJ/wZr8hqcs8mNoPD2B7MjOuPkyByHxBHIMtpSnvU=,tag:KSI8NGeDGZH/8ZwVqy4hDg==,type:str]
            password: ENC[AES256_GCM,data:ARW38U+iqL1vANxnM/d/GQxYNuY=,iv:sP22r3q8giXBC6ylJhMefKXaTDob6ih0tAIxxmHdGsA=,tag:YAmCElMyNcTRznBuC4Nz6A==,type:str]
        - name: dragonfly-secret
          stringData:
            password: ENC[AES256_GCM,data:5QI+sdnDKXRLhaTtbEAb,iv:khVWw+6KbSJTf2PmAXED2ali9CWMytJneG53GZ/pqFg=,tag:Ivl3hbvdsT2PhgSKlPXJhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyN1ZzTDYyelR0bXhUdkhT
            YzZxb0FrM3duUkJ1a2JPNE9xbjBUNS9pRlhnCnFWTFFJS2ViK3NOOUZTSGFibGRR
            WTFuYyt5YWl1NHZucTY1R0phNUdEUm8KLS0tIElteEprNVVlNG5hYXpIZi9URkp0
            SnJWTkFBRmhTL2ErK21KR1FzY2RIWGMK3vT9qHf+EAnYDERGL2UtyttOXSLYS7Yt
            04GLj/tNJpKaNILM90wSVG/ul5GqYnS9kwgrrpGOf02pBLhSGvp8GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T12:18:08Z"
    mac: ENC[AES256_GCM,data:/CRol/XvVSrEjENi+MYVZa+IE6N1cbZTXbDKyhp6P473GhinMTQz/8XzN9/cZ/WsdT08miPb7g+PUX8Kr9yGLpgje/Afnf/mcxVIcy/x4amspdm1PrFY+cxrTq9mx11TYgNB+B0/Mmwk3kSnUH9DYWVwq0s2o1k0GcIWmMG/28w=,iv:uN75eWrCSfxgzKMAB9j0pty/53tnCCP++tV2bH+7Weo=,tag:rjTCh8wDteHiFwhqk4RTLg==,type:str]
    version: 3.13.1
