apiVersion: v1
kind: Secret
metadata:
    name: gitea-homelab-infra
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
    annotations:
        argocd.argoproj.io/sync-options: Skip=true
stringData:
    type: ENC[AES256_GCM,data:nuAE,iv:WmIWnolRS85fbHSVGODUPH9FpVBu95sj6nVNrtek9gk=,tag:gLmaDmTyccx554F9lbhqHw==,type:str]
    url: ENC[AES256_GCM,data:Pea7N7COhj5TVrLf7cs8Mi/GPrfshkB0LrZBbAJz1sMNG2bz4vuYBW7XmInJncs=,iv:LTy4wpOY52bi5O0SRmKWk68v495A54K/BWMztb+udl0=,tag:8PBxH+cvoYmxr6bJkLRrXw==,type:str]
    username: ENC[AES256_GCM,data:UYu2HUlkwDM=,iv:l1i05PbX+kCLlXr4q+mQR25/7Pbm0KtshbRbgIG+OdA=,tag:K/NRCMSBrv3YmuyYarblSg==,type:str]
    password: ENC[AES256_GCM,data:mNbYzpSXEKlluCXA0cY7BLSKf1T4JXyR6Sgj9vOXGg59swsVD4cU+Q==,iv:xEi1FZ+BRgCPdIMU/DOlziHwOt0PjQAm7oCvAQFrTqU=,tag:+iNyXYvl8S7OMytYBzD0pA==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRHpnelFPbmlRUWRlaHFP
            dzdOQWs4TXdqUFdOeFZob2xwSnUwQjBHT2hFCk5XMlZrZXlDbDRHVEVmc3lsZjNo
            N09scHdDR3MyWGRINW9VbmpvOEtEVFEKLS0tIDFuMEp2YWwzVFR3SHBRK01lNEJv
            VE0xaUM0ZTFlWGd1aEVFNERCVWJkVkUKog2zp8+QvEGiuLvbXQhnxeOKP2FTZlJr
            T7u9huen0i/2kAM66DiI3pMEcVLpiaaxTx6GcOKOXNUlBeuuzvkKsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T16:35:59Z"
    mac: ENC[AES256_GCM,data:AxOrLVjtvYSLeMfoe3Cw2htQBr3gMQQg010ZmaLR9U33BwJmvfRY741rhOtDoVzf9fGoiSrpQVTQpwWO/LGQf4lb3dJ75vvrC5LVTrRBXKtTagG2Gk45pmQPjklC8wk4w+fJcRf/mSsDpZiSPqqNwIDuIdYCnIEoFBwy0v9b0cM=,iv:jXyoP24qO6Lxl/2l/MykONQoJ7qqrbQ/BrmL6zRNY4c=,tag:8MrwsNlUOGsz6nwfEb5zoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
