apiVersion: v1
kind: Secret
metadata:
    name: gitea-homelab-infra
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: ENC[AES256_GCM,data:BBT1,iv:vZdgrAsFHOoe0wT5/Envn1P//HQkewv0vCDMc2jB/Xg=,tag:CV+3+nvTgLNCazB4SNKf3w==,type:str]
    url: ENC[AES256_GCM,data:B+qCgLb1tqQh9pGZ7JuaDAEYEqR95n/lJthNKX88gn6Zyk2UuK1rIUbaF/41/vY=,iv:a6lMeMPqcp70G1KKr0oT5h1MvnW0wziwTjjZit9Dqlg=,tag:+I0FGKNqmJ/SaWDzFJpXxQ==,type:str]
    username: ENC[AES256_GCM,data:MlMLJTbT6xU=,iv:d0vSQbfnl5M4BzmL2TXBJKDib8geuRsf1zfENcFBHXk=,tag:NiOv4f8P/x7vMp5la+1nuw==,type:str]
    password: ENC[AES256_GCM,data:tPg36KRi6KgDvcg8KpIxg0FNdjfZid+YXRdq2MH526gjqLuQEWSh8g==,iv:gy9fJGu9tcEKWaIVfNJynpLRNoyeq5Oa/TN6jWVC3YM=,tag:TcEKZugG1/DAQdY2xC6kag==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaCt6YVFxOFVGU0d2d2pQ
            WFNsbFN5bGZqakdjUXRBVzZDajVjNGJMMUdJCkVES0ZBNjcvRkFYRU14RlJpRTh1
            UXE4UTMzZHBIUHYyZUZsMHR3TjkrbXcKLS0tIGI2ZWhMbVNwdzRvUm9EKzNDQlll
            N0IybjMwNStJd0dNdUpJN055ZXNhOEEKtlNvoZZ/j8wE/jsluKXWeIwDwNCfoRfa
            3Kph2u1gVfvser+2oR8YVyn/0jkTnkajFUmzgvYt79fvsQbr6GVFyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T15:50:10Z"
    mac: ENC[AES256_GCM,data:lL9OgBcjBMXQjup8fN4K+LzYGxord3ny8h32RLJ5SJ2aaVEFcTINM3g3V3apGRXk23mt6xsiaL3VkdiCNg6ZXoOpNF9hoF0OAZ54IMtoavjsFE7oIb9N9bJSX1ujeDwEoOYlnLLMpdxfTVwrCMybrpO/REQvEsunRDSUXqY3PME=,iv:i5y9EC0rESqIMqGONw6O/+IEu7XGuMN6N2Y26ryTb+w=,tag:hiQTFT9SmB7fjfUI2/pfSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
