configs:
  params:
    server.insecure: true
  ssh:
    extraHosts: |
      [10.0.10.150]:30009 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/clf93dGeYwHGdT+E88jwyJmHc/J+QF8XygAM8EorWIFCz/XBX61wjcEy7V3WJXniTTMJVsoqEKbxW6ud9A7HlF4rgJkizJ1IZNfJggYKRWMHT3YgvLbU7zCC64vqAcfmTzVVDzy+Rv2iFKDJt64g6t5cad8bP0pnEtNtQUdI07QRY1j8HxhBJx0TQWoDFZY4bEGsTe9o+H3wgQPZwLJwB0I85qYljeT9fOHg5PuBekmXD8YT4yxR5goIbHYE/OBG/voicfAO9DbHyTIcrFGiepgQhV9hWPpi1+lZXh65B0JpDjRUSmaj9sKLytkmpKaITh6c2m2plxMyDL5TJtqUj2mV5MZXXHin8PpPPVsyn2gAlNpTVZ1MR4PGSnNzcNvFB81PQ3DH4A2p24BcTD9UJ0YagkZhlHL0GyvwTVcYRjnMysRkicm93cP6V6DSH7E552payhGyID4YLJo7vCeevydbMsWmQwnvBsFhzFi9vJSD5Km2ZVnPr02p8zuZ2csc74op45kaKFrKigwZi/2pl3BRD45d9qXqFdkIiMCfObjLSnflGSiDgMyKRW+PiRAV8rqkNDAnO0pw0WEUxJIPupwZGHqlfHBcaJgidLkuid+Q9S+0hkkDz5/wF9HaKLopgbF64sawFnWL0pLJKTCratEugfN1rMhPSm0vz9wV1Q==

server:
  ingress:
    enabled: false

redis:
  enabled: true

repoServer:
  env: []

crds:
  install: true
