apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-config-nfs
  namespace: crowdsec
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-db-nfs
  namespace: crowdsec
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 5Gi
