apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: crowdsec-secrets
    namespace: crowdsec
spec:
    secretTemplates:
        - name: crowdsec-secrets
          stringData:
            agentUsername: ENC[AES256_GCM,data:SYMmn46tZtydn1EsJmLSLyw6QiUTQw==,iv:8LSDI+wbdvuL4mau1ItTs7RNz9mqH1yXfHd9X+/IQeY=,tag:0LnMbHSg+fUKtddWuerJyA==,type:str]
            enrollKey: ENC[AES256_GCM,data:fRAk6X2HpLXrX2KgBepSoir55L8CZqQjYQ==,iv:HLkAYyfkWdsJyqwGPlh++ZsPR2FC4TprA9JSZKIW54o=,tag:ibNwlDsthmLxfGI0p9d4ww==,type:str]
            gotify-http.yaml: ENC[AES256_GCM,data:N8PlIpxMGpxgqKIKVhXSM2je42xvnLMdj2EoaMWclVedGz3tfzAzJVcjqzUvDdWLm29njprykDr+OltXshiTwZ6pLZLYVU+p9CZ2xWNcC8ZBwPdkuuWKdkgfmG3zj2UqPCcpRjSGuIOX+01NOgD1a0p3cqyWPejhmIIEqEbIK5BjH3Kthq7u6rFjodjAb9Xh7H/dIuF1N00FnzTagHHe/te4J+05HpP0islsYRdhEpRnvXvRc6rYejRyHxx2XUc2og/eBTdXEO2/awRo8y6exGGQqQCBPm4irhJZua/LySTuRzt7hIqBoMxjmIID00CHHbLP41Of4hQT2nbtq98Jf77VLV3ECcdF+qz3wiNczdJun89LtEbEznW1jh6gURc/vM4I1BacWf6ID8I0aRz+Oxj6yCOrnQgERW3HXyqcUMIb6zgYaX54SFESmhk7pu5D0Me+oG/9LYDDF3zGsKLbdA==,iv:jFTyp2WwqGZ8S6sgLqigSVQfPOjsKdhOBpAsIHQz+7c=,tag:J0/WGUFryTwfGHhMRJXKnQ==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWjFPNmp1SUN5dURNbzJG
            czNhZk5jcUE4aTFWMG96SktBMVBEN3U2WDI0CnE5akRwYXJZc1h5eWUvOWJGS2cv
            KzJEakpRY3lvSEVqbzVvRUZRbTRua28KLS0tIEhDVzN4M0FvMmJuR2t2UVBnc29h
            YmlkVVRyRGpYbHowSktxNmEvWWFwSXcK272Yiw4R0SoHueH+QCDnD9IlAiRnwdqv
            J/tpriaZm/sVzRBMLtaWC6ZfIDUNW7Zdc7wPjvNyG7PjOPQzveAEIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T11:21:46Z"
    mac: ENC[AES256_GCM,data:XDKDgo13QaFHpDfFUd2omCn+1RUQCxzuNgY0Q19jRrDityzjshYg5OfN9DFSq5uHQTBLNbh8Z7+OfpUJ0+FYjWDDaKhZ4FTYApb+n4h767WH8BpsWwE/y/OJFcA6nRACn1BP4HMwW5Qhmd26z2xs0mvAFhLaXX6UgtAUdX/yHuM=,iv:kS3zf2//LD88iG5hX88oY6i1NOXzfemwHshHVAA5xPo=,tag:WzQwacyyjGN9f81D7N6tRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
