apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: crowdsec-secrets
    namespace: crowdsec
spec:
    secretTemplates:
        - name: crowdsec-secrets
          stringData:
            agentUsername: ENC[AES256_GCM,data:SYMmn46tZtydn1EsJmLSLyw6QiUTQw==,iv:8LSDI+wbdvuL4mau1ItTs7RNz9mqH1yXfHd9X+/IQeY=,tag:0LnMbHSg+fUKtddWuerJyA==,type:str]
            enrollKey: ENC[AES256_GCM,data:fRAk6X2HpLXrX2KgBepSoir55L8CZqQjYQ==,iv:HLkAYyfkWdsJyqwGPlh++ZsPR2FC4TprA9JSZKIW54o=,tag:ibNwlDsthmLxfGI0p9d4ww==,type:str]
            csLapiSecret: ENC[AES256_GCM,data:Z53j0uGaZPZ634NxgPYuQNtmYup6aCmZ35xoBYoXbndUlIRNQQF3BWDpzG5qjIIS4387SvTlwil7TqrjOPGyZQ==,iv:E/x0psEQgHiHMJrqGPiJzU/FY0z+nrEtRgs+MaibTGI=,tag:EdGm1MRk1wMHruPThySqpA==,type:str]
            registrationToken: ENC[AES256_GCM,data:JafFk60BBIhJn72aXZnodn9Aq9u44FySSg8qebmCAUGkQp0Yafv+r12k8IhkXIz6,iv:6VHOfFzqjwBdTEs6TDe5krDhcyZmd8xjagC4V8DSFz0=,tag:hUGV8Awlj61OjR918sES6A==,type:str]
            gotify-http.yaml: ENC[AES256_GCM,data:N8PlIpxMGpxgqKIKVhXSM2je42xvnLMdj2EoaMWclVedGz3tfzAzJVcjqzUvDdWLm29njprykDr+OltXshiTwZ6pLZLYVU+p9CZ2xWNcC8ZBwPdkuuWKdkgfmG3zj2UqPCcpRjSGuIOX+01NOgD1a0p3cqyWPejhmIIEqEbIK5BjH3Kthq7u6rFjodjAb9Xh7H/dIuF1N00FnzTagHHe/te4J+05HpP0islsYRdhEpRnvXvRc6rYejRyHxx2XUc2og/eBTdXEO2/awRo8y6exGGQqQCBPm4irhJZua/LySTuRzt7hIqBoMxjmIID00CHHbLP41Of4hQT2nbtq98Jf77VLV3ECcdF+qz3wiNczdJun89LtEbEznW1jh6gURc/vM4I1BacWf6ID8I0aRz+Oxj6yCOrnQgERW3HXyqcUMIb6zgYaX54SFESmhk7pu5D0Me+oG/9LYDDF3zGsKLbdA==,iv:jFTyp2WwqGZ8S6sgLqigSVQfPOjsKdhOBpAsIHQz+7c=,tag:J0/WGUFryTwfGHhMRJXKnQ==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWjFPNmp1SUN5dURNbzJG
            czNhZk5jcUE4aTFWMG96SktBMVBEN3U2WDI0CnE5akRwYXJZc1h5eWUvOWJGS2cv
            KzJEakpRY3lvSEVqbzVvRUZRbTRua28KLS0tIEhDVzN4M0FvMmJuR2t2UVBnc29h
            YmlkVVRyRGpYbHowSktxNmEvWWFwSXcK272Yiw4R0SoHueH+QCDnD9IlAiRnwdqv
            J/tpriaZm/sVzRBMLtaWC6ZfIDUNW7Zdc7wPjvNyG7PjOPQzveAEIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T13:13:05Z"
    mac: ENC[AES256_GCM,data:03vNyX09WnLwSM/9il+9CnSo+2R/esRS6Z1l4ZsZkGYtPwRh6S0UvD9Lt6ITx8s2gKIFcOHnNcZQwajJoBWGPf516j4IoO/yJptPv8OLtjiJ+0wecY6tgBPXBUaIkuVa9C8OuT76cGMqWz4L/5OIs3I/+wH4t2HTZN6nkIWbJv4=,iv:l2GRxn1u04M0S42dUFAexFrOk5bi+2w5y0PcIypkOpE=,tag:lrfO06zHEP+cc4ypwNFvyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
