apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: crowdsec-secrets
    namespace: crowdsec
spec:
    secretTemplates:
        - name: crowdsec-secrets
          stringData:
            agentUsername: ENC[AES256_GCM,data:SYMmn46tZtydn1EsJmLSLyw6QiUTQw==,iv:8LSDI+wbdvuL4mau1ItTs7RNz9mqH1yXfHd9X+/IQeY=,tag:0LnMbHSg+fUKtddWuerJyA==,type:str]
            enrollKey: ENC[AES256_GCM,data:fRAk6X2HpLXrX2KgBepSoir55L8CZqQjYQ==,iv:HLkAYyfkWdsJyqwGPlh++ZsPR2FC4TprA9JSZKIW54o=,tag:ibNwlDsthmLxfGI0p9d4ww==,type:str]
            csLapiSecret: ENC[AES256_GCM,data:Z53j0uGaZPZ634NxgPYuQNtmYup6aCmZ35xoBYoXbndUlIRNQQF3BWDpzG5qjIIS4387SvTlwil7TqrjOPGyZQ==,iv:E/x0psEQgHiHMJrqGPiJzU/FY0z+nrEtRgs+MaibTGI=,tag:EdGm1MRk1wMHruPThySqpA==,type:str]
            registrationToken: ENC[AES256_GCM,data:JafFk60BBIhJn72aXZnodn9Aq9u44FySSg8qebmCAUGkQp0Yafv+r12k8IhkXIz6,iv:6VHOfFzqjwBdTEs6TDe5krDhcyZmd8xjagC4V8DSFz0=,tag:hUGV8Awlj61OjR918sES6A==,type:str]
            appriseUrl: ENC[AES256_GCM,data:oZJSkMBkanGPgjhogKkot3PjgvCytcmquthlOaEB1vmxrsWE/1ND6EeuL55Jk1mbeVwcREk7piAhfx79/fushjvgJ2mpynrnnbEO3XFlnIn56NkfTq1wi23dnVKfGrnetpcs,iv:fTkIay5Qvr4etObTIaGso6PKcqDsEzA0tVI9i4+QlWo=,tag:bvpEPjDXYXzlBF5yGtihAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWjFPNmp1SUN5dURNbzJG
            czNhZk5jcUE4aTFWMG96SktBMVBEN3U2WDI0CnE5akRwYXJZc1h5eWUvOWJGS2cv
            KzJEakpRY3lvSEVqbzVvRUZRbTRua28KLS0tIEhDVzN4M0FvMmJuR2t2UVBnc29h
            YmlkVVRyRGpYbHowSktxNmEvWWFwSXcK272Yiw4R0SoHueH+QCDnD9IlAiRnwdqv
            J/tpriaZm/sVzRBMLtaWC6ZfIDUNW7Zdc7wPjvNyG7PjOPQzveAEIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T09:45:34Z"
    mac: ENC[AES256_GCM,data:cYt9SmyjcLlVK3XMSgJT+DP+oHk7Co1lbISvTc2T1/0aizmLYnNoLw/PNXP21LEsZrFpWwTjF8yajrsn/DuNWG8SR1WP4owT/IrX6nrfkKe85WnYm6hrsBl63gYZy9kd+Tl1OZmjHRq3g0d13RGEPJM4vBSmgzHddAAjjYQjggc=,iv:PYhtARWp958aHq1ND4+MtQbhdg3DaXP9ZHNbOIxeiew=,tag:UwUYqRSm/u6Pd0ETrO/LvQ==,type:str]
    version: 3.13.1
