apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gitea-runner-token
    namespace: gitea-runner
spec:
    secretTemplates:
        - name: gitea-runner-token
          type: Opaque
          stringData:
            token: ENC[AES256_GCM,data:ZE3I/3g8Fv8LtDyxmWiLQYjQIrY4fgYzYqGKLBlTXwOjXVHAU2yEng==,iv:a8V7JV3lqtOGkAgEKdzYA4JvUkj3yOFxgd8fuTm4mMs=,tag:JAPiR/fptZxXlGu8m8T3DA==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOHB4bThobG90QTZ0UDJ2
            WmxncmFzL3YyQnRNQU1GdnpTUnJ4NTJrT3dzCkt1QkcwblBFUEpvVUtSSHY3WDVv
            dmFhR1I1THZWMkFPT3pUcGUwNlNJeVUKLS0tIGNUYUtCbFQ2ckIveStWb0EwSklB
            TElmM2h5MHdTSWF3SWhESEFWV25rdncKDkHFgAdmxhlXdShsw6u3jGG4oSwHtUH8
            ZqMSbMOlb6M3BqUhpe+RRpwyytBgwc1PvnwOq8M5HZxCJfexAQIMVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T21:23:32Z"
    mac: ENC[AES256_GCM,data:hFYsvkF7aG4P2kAwK9Z6FRqbQesBv5NwIWBCAhga+6YgDEGIVei0Iwv3gjfvZTcMl+4LpQmgRvQm5f7Alcz8Xwac0iSiIH0H9Z2W/chGjI497ZITj5hMIeThiCpV1F+4N791NPiv+tdR6uHqnaghR21TLEb4bErNIiIG+xVQfkA=,iv:qJyXZtBQY5uJdXYCmWGCN/qtqXtj1VSm3TAUSpVA1kk=,tag:8gK0UbcRS6PEC0GRr/9CUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
