preUpgradeChecker:
  jobEnabled: false

defaultSettings:
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 1
  orphanAutoDeletion: true
  recurringJobSelector: []

longhornUI:
  replicas: 1

ingress:
  enabled: false

persistence:
  defaultClass: false
  defaultClassReplicaCount: 1
