apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dragonfly-secret
    namespace: dragonfly
spec:
    secretTemplates:
        - name: dragonfly-secret
          stringData:
            password: ENC[AES256_GCM,data:pCD0vz8cfzbTTsa31cb1m62Mw/A=,iv:EBUZK/Dpts+fD600vmjj0z3r0WIfJP78A1r0DTsYURU=,tag:Chc9k9Lp+Y9tduWKNpyTiA==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUm8wTTVONk1sQzZYV2VB
            N21UUWd4MTZpd3duUTEvWlVZakxVTUpsSDFvClZDbFBPV0VwZ29JKzZId0xlb0VG
            bTByM1hsMWI2RkZ3V3NZL3VjZlg3SEUKLS0tIDBTTGk2S3VhMk5UMEtXem56cDhO
            Mmx4SXhkNHE3SU5QYW5ZRjllQ0RRQVUKlvo3CVeQSWDFrKdAek42A/v7psUJjgM1
            6kxXyTIxwXfeytWRH8Ar6DlVvYagF7CtQJzxpIxgUwDit1fj7gn3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T15:22:24Z"
    mac: ENC[AES256_GCM,data:lgNTKhjjBnd3Mqtpi+yHtEsuoR7UpG49gHPdyA0YR3kWkVann8BoC/gzeyVj2inVO5gNLqO5fMHXRh1chCP0VTov1akzyZ7YVno9/P+cm/P1UUgypovINLmIs7myY0DLypnP1cFsqEWeQQ6dUOLytouvN1IdYH0piz9uQfZyd4g=,iv:C8/sjBIGqgW8whIC9a9VVFBpTu4kBaO7w2un0LNeDw8=,tag:ThRs6wZHAN9MVXtcCINvMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
