apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dragonfly-secret
    namespace: dragonfly
spec:
    secretTemplates:
        - name: dragonfly-secret
          stringData:
            password: ENC[AES256_GCM,data:cEBA146Yfk5nUjPFT4q9/Ig=,iv:T8nF0Jc0viPyrThbJmR3c0m/le4aKZW4k57MS+BwLDU=,tag:QekA5ZLqKO4x7EujcSkjNg==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUm8wTTVONk1sQzZYV2VB
            N21UUWd4MTZpd3duUTEvWlVZakxVTUpsSDFvClZDbFBPV0VwZ29JKzZId0xlb0VG
            bTByM1hsMWI2RkZ3V3NZL3VjZlg3SEUKLS0tIDBTTGk2S3VhMk5UMEtXem56cDhO
            Mmx4SXhkNHE3SU5QYW5ZRjllQ0RRQVUKlvo3CVeQSWDFrKdAek42A/v7psUJjgM1
            6kxXyTIxwXfeytWRH8Ar6DlVvYagF7CtQJzxpIxgUwDit1fj7gn3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T14:18:29Z"
    mac: ENC[AES256_GCM,data:1aRDyOBjyQjf79wg6yaC1Y+uNjT4PCVLJN7r20uc9P2jJxM+QuVd99yHV4D9KiHWc5RqGd/7qYgB5ewDLHOOAy4GZt+5vkLvTn3NbFgbkNhZlbyptwCABlak2oE+TiiZlVgcE8lDSkK4ivJR48mMckUTWBKwJUPbM+6nXOinytQ=,iv:AvFokccxO10DpRzQWS1P5ncupXWur44a2fIMS1CwW8I=,tag:RLUbh9rsbizbODTRfqiFrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
