apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dragonfly-secret
    namespace: dragonfly
spec:
    secretTemplates:
        - name: dragonfly-secret
          stringData:
            password: ENC[AES256_GCM,data:QRdVhnUN/0N4Zc1uWERy,iv:GHe8HZznNrYfE0NkqILPeiS3PO12TXD7hR6NM7cFrHI=,tag:0klIoQvi8lpqSExm6PVTrQ==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUm8wTTVONk1sQzZYV2VB
            N21UUWd4MTZpd3duUTEvWlVZakxVTUpsSDFvClZDbFBPV0VwZ29JKzZId0xlb0VG
            bTByM1hsMWI2RkZ3V3NZL3VjZlg3SEUKLS0tIDBTTGk2S3VhMk5UMEtXem56cDhO
            Mmx4SXhkNHE3SU5QYW5ZRjllQ0RRQVUKlvo3CVeQSWDFrKdAek42A/v7psUJjgM1
            6kxXyTIxwXfeytWRH8Ar6DlVvYagF7CtQJzxpIxgUwDit1fj7gn3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T16:32:00Z"
    mac: ENC[AES256_GCM,data:4smGaVf3Kpwg4qqnrKaobsJO9bqVw3eXxNtAyOVsi4b5VZ/j/Z+UBNZn8hjYn2tokvBnmQQc9duE6giAPy4mO0q9OVpvHlyVkmVAMtkdqrLsefcy+eoE/4FZdUZF7tKvuWi+ZNi1A6JFWPTJO2Z/Y2om2ip9Un3vJMQuWyZawpU=,iv:LqtvK5d9VGwVYmNWdvRh8Z/IcYejbE3/de7Fi2osDp4=,tag:XQ36uN5Mlf33SwEQBrOpDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
