apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homarr-secrets
    namespace: homarr
spec:
    secretTemplates:
        - name: homarr-secrets
          stringData:
            SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:vmpa2m1+sJzrjCSza/p+BTuUdDpETmNydguFs8eSevSPlWhXAiscVy/McvJGHxIm2CvsOk48emqVccZo51D2HQ==,iv:UdmFMhWnPTdOSnC7k0PjhfyKe331tsVtpMxsz2tiGfE=,tag:QjCwQB0+wNBzG/WPN8IlAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZWtLenRiRGtCNEVMMTdV
            dUhGRUxZQ0kxaE1yNzhZcWRpb21zSEZxem13CnowRFY0M0FySW5kSzlabHI1YWlH
            TTVnNlRKeFhZQ3dWUnZUY2ptZHovK2sKLS0tIC83ajd5Vzh2NVlIcGZlV3hLMzZI
            UGk2NGQwdFFEU1RQQm1OYnlMN2ZzNUEK60skOt04VVTJDE4/HjAYQgBcDtTMr7la
            Z+DVAdL/ztEwpFpbd8Y9XKar82bny9HgwQe1lDZJTO17gseRjTGJvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T12:39:37Z"
    mac: ENC[AES256_GCM,data:HYfCTVg2Ads3Xmb6DgFerN/Z2Txe9P+PPiYs+nTIoyY4MLiF3OVW9NWBvrHoh4o7iBLDiujPmUeSJF+4fC0AHTj9rKDd4fgAeceUhZruaidszLnQ4bDk5o5/HlHV+r0gted/CVtrT0dZCjcHUcOOP9bEG3ZnZ8nZtSDn7we4QB0=,iv:FagGvfUep2EytY9xVCJoIMQoASQ+f7t92QEmjCeVGww=,tag:PG6I2dZhaxD7Boy0su8jKA==,type:str]
    version: 3.13.1
