apiVersion: v1
kind: Secret
metadata:
    name: homarr-secrets
    namespace: homarr
stringData:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:EoDjxbu2GTYqt0KQuaY/5hit2xZFb/vJ2HqR/C2WQZ7Q3Gc6HC9n7Ovw2RTx5b+YYj+OSZmK4Ie842OlkvFbWQ==,iv:7P78ZENgGkuAg/BdQrU+q52oug+KdVSF5PnUaPFl2C4=,tag:dFbo4euTa8AaCZR6K5JmiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdUFuMmplUVZUR2xZYmRx
            dXZ1YTE3dk9pNUF5VmJMVUhMTHRLTjN4MUVVCkx0cGgrRDBVNXFialF3TmJsUDNU
            MkN0MXJkZS9HZWtxN08xN0lVU2NWMGsKLS0tIGEzTVFvMXM2MSt4S1RIVmpGckZo
            bURoUWthWTh3VFVuOEh2SHJ6b1pJRGcK7IgZi/rXH/4pt1Yc2EhNZNjL601aS0Z7
            rIdgxm2bsw5srxfL9uxP+IXNPaW3TKK36duqwsY1xVDhsHrTQ+ww8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T12:22:11Z"
    mac: ENC[AES256_GCM,data:JImw3FiMtRIhqpqNtXjeI0o0jsTN+RfJ5uppnKVtVYS89D83JXU1ot015LvZIb6iDAg8KQPaiDOg4xq0+O1COwciVkCkU5VWrcrd7dgGUJys3mZ6CEjKU9xOcdhif7HO3rQwmCehcitxSqPBMAZq9j99CocoZnRU6ep2ISTEASI=,iv:IGlUs42BqborWdZuVsVB3wRgyEWGt2I9sO/umWGneC8=,tag:jmvOfL4phs4FpzXE7qAkqw==,type:str]
    version: 3.13.1
