apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: garage-config
    namespace: garage
spec:
    secretTemplates:
        - name: garage-config
          stringData:
            garage.toml: ENC[AES256_GCM,data:IK5zK7zE2KTEqG5ypTjM2nUwBmC/r1jlicmvGOcrSFH/xI9Hzb2lW1Vh72rJtB4xGQXP7hr6knhn50hRdBavAW6/VRBaR4qeDyD32S7dvTZ5TlP2zY3oghpAD9BNCJF2spdxLle5KkpCQhv2Fk7IVf50RIZSLdUjUutmvACH+wGmxoxPORgfQZrTsIa5A3tqPctnyHk2UH5Svxxj1qd4aDo+VPluwCmRjkYiYpASTO7AseXZUptrOM5xmWBmFZDUHNhct7/LG405Ukh6ajc8WtqDqzKFZK0NiY1Vug/xVMu9fm6hrbWEti9CMhXQ/B4IDhxbAH2YQ78DIGO4ic02If/U8+DWks/rNdYLIyY/03i5o2CIuvtq3aUsdkvuyLE7SXDIVOKXcH85Lv7WBKGrp3cvvOoKPMuauhK7JHvim/uy3AIBwKCG2HHwNumC1ebkRhBwLOBNX2iEnrl5AAX/OQkYowQ3AmgPBAwFo142HmY3QTXbTNttUN8Jn3bYO7M3MNAQIyawXbFWQot+C239NcKJ31ZUVJcf0b5zIp6/EINIUPefyGo2Q2YvRNNtXKcmHBph9YhqhQhe1GF/iR0lMAgHqxF4fPUeaa9jxhIjm2dTA+OzaSPOsbZT2YYyHAe9UpqNX9e9klVnc9YS/iHdz3trQgpZtAWU2ujbjFVJNWLQs/p7uUEMsBqpcGCgDEQERF+B7ExQjy5Bd36dPwI3OY2h,iv:yAfrgQGOWkRaJ433aVt26sLwErXQUz7Ik5+BU7tcpZc=,tag:MAuaKL0+hw9nBdTE4yCUjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdEFHSktNVUUrdzFJU3Nq
            QkxqbnJKTnU3UTVocFNQT3Y3dFcxdzRMVno0Cmp3NkRqZTFnYytmZWhlYUFBbmZt
            bE5rL3RDVmJXR0oyNElPVGcvVXhJeFkKLS0tIHdsTFRTeGlUZVl4V3hhTUZDV3lU
            U1RwUk5WRWxwa2hHUis4YWhRL0QxOTAKLtEQFxIdG/BfEC1JT7uegVMD8pEgkF/N
            enFXKsKLejnQsq5s1fkGmYPEsOaJvufjbObF3yewOZ2fD6s67/Kcog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T15:35:35Z"
    mac: ENC[AES256_GCM,data:9fIloAcE7BoKou8Qjw5YJgwLChtPh7T3vVrDt1Rvb0xeH34RmSTnO/ryKAfbkDrQiCMgahs2VdKliwOjIQYMfVEXMVgAvZ1R92/26hyyOZy/dUthVsi+1pzVPvEK7QytXc1mVk1gqaGWU3kMkRN8lz7w+ZudrxUZ2LCh8x1o8U8=,iv:YuZS9qbQA8k/mPMXf7MpDlcm+xzwijn8LZ2qNdedlQs=,tag:YIAcVcIzV8AmcV2i2qOHvw==,type:str]
    version: 3.13.1
