apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-secrets
    namespace: authentik
spec:
    secretTemplates:
        - name: authentik-db-credentials
          stringData:
            username: ENC[AES256_GCM,data:tAYwmhaauK0=,iv:9wWtGz24BF5dsG/C+4b/QH4xJxLt2yTc7tDN3P4ygBI=,tag:LNm/ceVTlMqfvIn8XaNVLQ==,type:str]
            password: ENC[AES256_GCM,data:bE6z8jQVhbHfWphEoz64uPI0UJs=,iv:NNBkYXnFKHbQwNGqK64jADI2qfmYveUQv4Wq9pR1KLY=,tag:QiUznyG6u/PNLTEz/IubdQ==,type:str]
        - name: authentik-secret-key
          stringData:
            secret-key: ENC[AES256_GCM,data:ZQqsTeLd806/GMUp9g+M10a2l5iGiPOKQGdI7yoEuQA5MIIWcEQeh+iM29jXqMPF63Ph0bV/ezVFmkMpJiBZXA==,iv:ORRpZ4lTpMlKzafoykuETJNqgF9pkRjEWWXc/WKfd/I=,tag:bk86fBr7Cv5LHvelPewr9g==,type:str]
        - name: authentik-smtp
          stringData:
            host: ENC[AES256_GCM,data:rlz9RAy5kmYK93uQU+g=,iv:ZeMBfbtp/12CPcW3VZsdhXxPM0QoZ9A2v5zKxfaCGYA=,tag:3XNDjLLWY1ipDsSOMcBCLA==,type:str]
            port: ENC[AES256_GCM,data:uLY2,iv:u3zvyO0+naJxhVwrw1TvVVdF6OyyGFvBAy3Xzf4CV+w=,tag:I9lTKjqos3FxuU1fHlkSCg==,type:int]
            username: ENC[AES256_GCM,data:1j2W1SV7Ys9xXIAGXQ6NHD6+dPWtCTJ8mok=,iv:r27+kXAs67J6WZzoooIP7sW0qwnRrWAdJoa+UXWnJa4=,tag:5+adeXdofAo4bnhpPF4O5A==,type:str]
            password: ENC[AES256_GCM,data:venYZ+GQTF0OtXBXfbtYzg==,iv:HGeYJt9pezXOyMqCFVmHbwhy/eKAZiZcISvt08MLnVo=,tag:jhkXHMLrFZfTxqBTLdNgng==,type:str]
            use-tls: ENC[AES256_GCM,data:F+lLEg==,iv:ulyk0geUH6tKFts9GSEqQk+/yMKFntNfszus4I7DGsA=,tag:X/1kMFLhCxHUP4AcBnGjPA==,type:bool]
            use-ssl: ENC[AES256_GCM,data:Ke+5dM0=,iv:FzlbO08aU7A6MpRbpeTtgnmlmHQjKjQSc5VHBVi/9xk=,tag:nxq8rkBdeDGnDZd1aGLfWA==,type:bool]
            from: ENC[AES256_GCM,data:dWxERnN3gS/jfrEa/uylg3PT1FNcWw+ZKjE=,iv:YJ/d/gs5MmdRl1+g7uvTzD7barRi2A0Uo5DT+DerMHY=,tag:4fqdjUB0qpVkXX9qya7IjQ==,type:str]
        - name: dragonfly-secret
          stringData:
            password: ENC[AES256_GCM,data:K9ypkDyhJBb9LYrBIvCtKU8=,iv:FJh+zCOG5fO9EQhBTs2vCO0XUL2hmOqSojzbbbvYJKk=,tag:2w7DbPlnHlsgMHBFLOnhtA==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdTNEZlRVVXNkMFMxSTFL
            dUZXNVRPVVo1SjZ6SldaTEF4cjVHdzlZS0I4ClhTVWlYSUpTS1duSXpnOEh4R3Nu
            Tmc2MG9BMldNVHkxcHNUWlJJUk8yQjAKLS0tIFVRNzRuanJGL0MxOUNVbG9aUUti
            QUQ5Z200cWtiY01VQjVxblo3QzY3QnMKtxE6x5f3KrdZ3JBD1+sQXfyXW9mAWKE4
            FX6o5QEf9bfRRd2S5v6VIgs9FgnDa2ntxhlE43/eZ+KcOMIuEArGJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T14:47:17Z"
    mac: ENC[AES256_GCM,data:EYJm5eJYTdTX9RrmJaeyKU0dUBTC4+M+4KSth3tHKxwM7WK76IN6oT39SJg4COPvfZOo6JELuWrqIjGgKGl2PTECR3sPZWkmTFiOHWIyI44X3WeDC1+UzQBfaM5wVD0kwjSad33SwZ2yEUpeJBy2CD1SdHfJTys+b49FCg+Tnao=,iv:s/4lVI8IHO1HxJ1xznxFd2dOWV4P+R10Yn/uKsgmm1I=,tag:qbOoW21CUuEfMEoFHjUw0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
