apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-secrets
    namespace: authentik
spec:
    secretTemplates:
        - name: authentik-db-credentials
          stringData:
            username: ENC[AES256_GCM,data:tAYwmhaauK0=,iv:9wWtGz24BF5dsG/C+4b/QH4xJxLt2yTc7tDN3P4ygBI=,tag:LNm/ceVTlMqfvIn8XaNVLQ==,type:str]
            password: ENC[AES256_GCM,data:bE6z8jQVhbHfWphEoz64uPI0UJs=,iv:NNBkYXnFKHbQwNGqK64jADI2qfmYveUQv4Wq9pR1KLY=,tag:QiUznyG6u/PNLTEz/IubdQ==,type:str]
        - name: authentik-secret-key
          stringData:
            secret-key: ENC[AES256_GCM,data:ZQqsTeLd806/GMUp9g+M10a2l5iGiPOKQGdI7yoEuQA5MIIWcEQeh+iM29jXqMPF63Ph0bV/ezVFmkMpJiBZXA==,iv:ORRpZ4lTpMlKzafoykuETJNqgF9pkRjEWWXc/WKfd/I=,tag:bk86fBr7Cv5LHvelPewr9g==,type:str]
        - name: authentik-smtp
          stringData:
            host: ENC[AES256_GCM,data:rlz9RAy5kmYK93uQU+g=,iv:ZeMBfbtp/12CPcW3VZsdhXxPM0QoZ9A2v5zKxfaCGYA=,tag:3XNDjLLWY1ipDsSOMcBCLA==,type:str]
            port: ENC[AES256_GCM,data:kcdy,iv:mzw+eNF+2itMuc8f6Kd2plDq9+xqtpve9MfYSDIaFDA=,tag:dAXvK1H8FkrTEeCqyEMaww==,type:str]
            username: ENC[AES256_GCM,data:1j2W1SV7Ys9xXIAGXQ6NHD6+dPWtCTJ8mok=,iv:r27+kXAs67J6WZzoooIP7sW0qwnRrWAdJoa+UXWnJa4=,tag:5+adeXdofAo4bnhpPF4O5A==,type:str]
            password: ENC[AES256_GCM,data:venYZ+GQTF0OtXBXfbtYzg==,iv:HGeYJt9pezXOyMqCFVmHbwhy/eKAZiZcISvt08MLnVo=,tag:jhkXHMLrFZfTxqBTLdNgng==,type:str]
            use-tls: ENC[AES256_GCM,data:N/UQXA==,iv:m1tg/dZ961sluxLcd/wsYLNmG2YPSE9z4x47lOPITPs=,tag:+1vDwYv/aHLLoJ4jhxm+Fg==,type:str]
            use-ssl: ENC[AES256_GCM,data:eR+yqgU=,iv:Qt87D6MfKDVqyfMc9+CKGG4jOnwniq5Ef+lV7pp8Sqw=,tag:PF7rHpI+0qu29C5BVVg9dQ==,type:str]
            from: ENC[AES256_GCM,data:dWxERnN3gS/jfrEa/uylg3PT1FNcWw+ZKjE=,iv:YJ/d/gs5MmdRl1+g7uvTzD7barRi2A0Uo5DT+DerMHY=,tag:4fqdjUB0qpVkXX9qya7IjQ==,type:str]
        - name: dragonfly-secret
          stringData:
            password: ENC[AES256_GCM,data:bE6z8jQVhbHfWphEoz64uPI0UJs=,iv:NNBkYXnFKHbQwNGqK64jADI2qfmYveUQv4Wq9pR1KLY=,tag:QiUznyG6u/PNLTEz/IubdQ==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdTNEZlRVVXNkMFMxSTFL
            dUZXNVRPVVo1SjZ6SldaTEF4cjVHdzlZS0I4ClhTVWlYSUpTS1duSXpnOEh4R3Nu
            Tmc2MG9BMldNVHkxcHNUWlJJUk8yQjAKLS0tIFVRNzRuanJGL0MxOUNVbG9aUUti
            QUQ5Z200cWtiY01VQjVxblo3QzY3QnMKtxE6x5f3KrdZ3JBD1+sQXfyXW9mAWKE4
            FX6o5QEf9bfRRd2S5v6VIgs9FgnDa2ntxhlE43/eZ+KcOMIuEArGJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T15:23:16Z"
    mac: ENC[AES256_GCM,data:H/WzEAkaZv3dgV8Ei8zn1NXlXMXasY9XvTiuLN857Ba7IHqtgEg4hDQItNZk87EC1MmUV9BApdBU2qDfpXodV6YW5zPw3/jlJYByyj36woM9DIg4yJyGsmQPMKY4nMjE/V2DnZZEMHsTTSeQ9Ny93X5g1YgDF0j3rKu99zraSJc=,iv:XbkbmXUnSoQrpGpr8LeLb7AP7gsGVXwxzjripINLFWw=,tag:YBiGjtp6dn41iFXNV0JmGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
