apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-power-tools-secrets
    namespace: immich
spec:
    secretTemplates:
        - name: immich-power-tools-secrets
          stringData:
            api_key: ENC[AES256_GCM,data:F36uZm91Xc9/2hmc9T4kxbWqfPepsp5OUsRDEMrv8wrKWU5E7Zu+uKo=,iv:oLcZBBfn8C07PlaxULkE+VRi4Gz7lSQh/Hi114XJ7U4=,tag:A2NtOmlbyWYwOyR3Aycpxw==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveURrRjZIa0Y3SjZyNUVH
            cytFUlpMUnMyVzZTUGY2SWR3VzZvdnRwd0VzCnFjdHlIVUVKMVhNQkZUYjJNbHRG
            anUzU3BVbmR5RDJOMHl5b2FVRFYrRHMKLS0tIHdGVmNDQ2hQTnF6elBvU21QRWhn
            dXZ0bEFnZ0lVOXdHTVJaRG5IV1hHckkKxEjyHxbTa0WTFsp804RIGH+sxtSqAIqZ
            ugGQ1FXxBlPLfRtNyvAP+eFjHuHJny8/QRM9GVHyWMtvR53LIp7Gtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T09:48:48Z"
    mac: ENC[AES256_GCM,data:pGdeswNhskJpJxXguUSVnaL8hfBM/g+qX0KkmxOx72cX/s5DRI5EVqjzdNmkfBz3rd1WHgUjgs3FFcxI/5eq1Elm5D2Y6mw1W5AJpW6ZbbGHAMUFF19AV/Ud2sxSDSVqQmL+tIxPb7AsT9fxA9Uob4kdu+kXMyYVbaODmSqnOS8=,iv:/n6W3brBNg6FtPNPES/ogdEyjVrcvSHJVt0XnOeJwKc=,tag:Z4Prrr8jpkQhvr/8IP6bVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
