apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-power-tools-secrets
    namespace: immich
spec:
    secretTemplates:
        - name: immich-power-tools-secrets
          stringData:
            api_key: ENC[AES256_GCM,data:9DCXfRHDlXUol7Ix/y7YN7Ll6wNgpC4Qmy7DHSErf6+W55mIDONq043e,iv:Y1SPzHWDelT0veZHzEgowk1LkIxDdph2y3KPkNmpVDY=,tag:EX1ktAGT/b4I+6uQO1AVrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveURrRjZIa0Y3SjZyNUVH
            cytFUlpMUnMyVzZTUGY2SWR3VzZvdnRwd0VzCnFjdHlIVUVKMVhNQkZUYjJNbHRG
            anUzU3BVbmR5RDJOMHl5b2FVRFYrRHMKLS0tIHdGVmNDQ2hQTnF6elBvU21QRWhn
            dXZ0bEFnZ0lVOXdHTVJaRG5IV1hHckkKxEjyHxbTa0WTFsp804RIGH+sxtSqAIqZ
            ugGQ1FXxBlPLfRtNyvAP+eFjHuHJny8/QRM9GVHyWMtvR53LIp7Gtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T13:30:29Z"
    mac: ENC[AES256_GCM,data:06OOmI31jhYTySdFjkOdPXWSt2Q1Un+zklytzbTfJ7d4t83YCOe2ay5lfO+p2zmtJryHsXIUwbNeohYhqHsOwaeoyVX27DtQdngLwFXU9dA6vbrfI94Wa2fKpWXQQ3gti9H9/eoVREwe92SJoZ0M0046+43mOXYD3t9WJpS+t/I=,iv:IxWymq80lHYMDXFMpqQobK0XSHSWeFyUi8dEaPzzWQo=,tag:aygdX8qkNczLRkhx5r1J8g==,type:str]
    version: 3.13.1
