apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: igotify-secrets
    namespace: gotify
spec:
    secretTemplates:
        - name: igotify-secrets
          stringData:
            GOTIFY_CLIENTS: ENC[AES256_GCM,data:/Eyj4au+sbk9d/n9HDnW,iv:/1ako+SH3mAV2hY+SPmvuyObINHlEotABl/vtABrEMA=,tag:pjNfV+5Bz+ZqStq9y7gRuw==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzR2p0TFVPQlI4eFlmY1Jv
            TmFrOVhSaG9JUTFOWTZvT3JacXI1ZUFuR0VRCnhldmZsdk1WRTN4dFFJNWhTYnlk
            cHJuV2FvdGt2TGR2WEhHaGRheXMrdTAKLS0tIHd3VEpOa2I4NitqRXB3UkpIQkx0
            Qm9FUXc3NkRBS1BxQVhKZUZmbHNoR1EKYlzGaPLelkMGXaxFwO2e3oU3jDI5cbUd
            BI+q7J7jqwehHueHQrE7gHgoS7cPOGmr9hDoLOV6ByO/Kx9ZA1dNLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:55:43Z"
    mac: ENC[AES256_GCM,data:VfB/Egw5f6pfStFKUYG0v7ZIVlwYeBsPx4h6cKojNhJxjfUm+YCSLGsafBKDN3R6YZgMrXu/2TxvXJYGRqEQF1Z1UdPmlgVv//NNZOlpQO0g8djTxQH/N+OFW4mhW9ryTjsjwezL/zeoxgd2mbIl4DExRN/7wREffyBDbDjHlYM=,iv:n2DrjrrqzKbZCSI4yotTyw05FZKyrVf5/xvGUsgik3Q=,tag:nEgJrpHAMxj7G5SQ2Hs/nQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
