apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: igotify-secrets
    namespace: gotify
spec:
    secretTemplates:
        - name: igotify-secrets
          stringData:
            GOTIFY_CLIENTS: ENC[AES256_GCM,data:DoBGynCcGcWl9iLekyBO,iv:urZ7M6/fjUr0IoloyCCJiApw43WUuDKu8P6nFLCsr2M=,tag:lgEyoL7xd4ei1lNG/4TAAw==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzR2p0TFVPQlI4eFlmY1Jv
            TmFrOVhSaG9JUTFOWTZvT3JacXI1ZUFuR0VRCnhldmZsdk1WRTN4dFFJNWhTYnlk
            cHJuV2FvdGt2TGR2WEhHaGRheXMrdTAKLS0tIHd3VEpOa2I4NitqRXB3UkpIQkx0
            Qm9FUXc3NkRBS1BxQVhKZUZmbHNoR1EKYlzGaPLelkMGXaxFwO2e3oU3jDI5cbUd
            BI+q7J7jqwehHueHQrE7gHgoS7cPOGmr9hDoLOV6ByO/Kx9ZA1dNLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T09:57:54Z"
    mac: ENC[AES256_GCM,data:2CGappDVlzmy+78APi1GY8Jyb9sOEdCy6skOhrMWitLX5ua86sJiPWMn/tkQDlm0K2O4RiqeySa5Z/6Fz3zmSZykVLnmC4KLoUFSUBUeniA7uY0QPB2hAOYSkDB5HV9oCMUMk7Zcx5kCm2G/ACWBJkjA36FNJGrRiPKUfpuIzx8=,iv:zpHGIvPdp6RvXvk8gS9JhJJdN5FGXH57mxIlVhIGZvY=,tag:Kac372geoT79U/MILXQKLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
