apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: zot-htpasswd
    namespace: zot
spec:
    secretTemplates:
        - name: zot-htpasswd
          stringData:
            htpasswd: ENC[AES256_GCM,data:4BtHIqMrFRSmFphNCRK3vepldNN2AUmev3mdfI9MY30vNCCnpHwmjqfohYzgrgO3YrPMtQYnxD0JeoZE/zE3sCP3AnfL,iv:fuLhWOIMY/ndI9xWuYnudFeu77oYxoyeUK1EbpBjzF0=,tag:OPze0DxgFw3+RBXq9/Mtkw==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZEVZZ1hETWx6WGUwZjh5
            V0FKZERxdnJBVXlqWGNiaTZ3cXpHVlhOdzN3CmQyQkpYSUJxcHZ3TTdhKzRDaDdL
            VjBzeG5kdjdsOS9odTFIT2RBN3BTUGsKLS0tIDNhQmpTdDF2QVdHeHBMMGJZQ3Vk
            SHV5YlFtaGhiSHgzZFV1Rk1LQWFFUmsK3+i/3tDn/taOAfvAos1K1IaaaTBGYq51
            n/Hv43Zn1Ud94Uxir/lBLu4otrTZHgvB5I2LD27S4+ol/4T92H9m1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T19:01:42Z"
    mac: ENC[AES256_GCM,data:PWPfEDJ9+Ugz5tvb43wgHOOYfOtfsbWHe1vkD6piaOCdJ+hIj4AEEWdyGlXJ+Lf4E5KfkSN87Updy7HzQwsCPtFrOt8Yv/bZo4/z83gZ5jVgEWtBKC5ndr9WG9vAxM6AE/Gd78F0965GJhcUAit3xiFjBhailrfrVmMrti3LlA0=,iv:JqByqU5a6ayZOnxTmqAoVOLY+PVF6aMvbKdG84zG8ew=,tag:fcs5sWbOEJgvK7ron6phjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
