replicaCount: 1

image:
  repository: ghcr.io/project-zot/zot
  pullPolicy: IfNotPresent
  tag: "v2.1.15"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false

persistence: true
pvc:
  create: true
  accessModes:
    - ReadWriteOnce
  storage: 20Gi
  storageClassName: nfs-db

mountSecret: false
externalSecrets:
  - secretName: zot-htpasswd
    mountPath: /secret

mountConfig: true
configFiles:
  config.json: |
    {
      "storage": {
        "rootDirectory": "/var/lib/registry",
        "dedupe": true,
        "gc": true
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "auth": {
          "htpasswd": {
            "path": "/secret/htpasswd"
          }
        }
      },
      "log": {
        "level": "info"
      },
      "extensions": {
        "ui": {
          "enable": true
        },
        "search": {
          "enable": true
        }
      }
    }

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
