apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: paperless-db-backup-credentials
    namespace: paperless
spec:
    secretTemplates:
        - name: paperless-db-backup-credentials
          stringData:
            ACCESS_KEY_ID: ENC[AES256_GCM,data:XqL/N/9MfFsxoQsjU8Hqmn0UjBej7G4MtFw=,iv:zDMCKL2iVEsOMiDwB72evYqqcLWAHgj0TznPJVdLOPM=,tag:/32MY+19yGJ6I5zWpj2Uag==,type:str]
            ACCESS_SECRET_KEY: ENC[AES256_GCM,data:lPtIjNomrQjFNY1TN7MkGZnfMbR/CiuZvKiLE7gjreWN04SVplaLNH7t8Md6V1A3QSGg6Njg7X4Cj5bJFJtkOA==,iv:Gp36AlRfqT3Iuo7jRQl3CZqELiN/e58S0qpNckiMdwM=,tag:+BVzFk/adxAXjy7XeeDEwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZ25DbkNmUzl6VmdOWXRu
            MWkrTnJsR29nWSthWHQzWk9yS1NuWlFFaUJFClpTeUpzVVVLTWkwVEVvdDhYL25G
            ZWhMd2V6ZWt1WERibVJnSUNDZG1jZ3cKLS0tIHRKSVBFNCtjazByQlVDUklDV1BP
            WDkvb3hXUHFEdnQ0dmlKbG8xZ3VxN3MKtSb88v5UDRSz/JnTXCvNoK4g0JgKTkzh
            qsjNIzTTMkvmFx61yyK76fwy8eLTazE3LTDSxEVp3hMlWemqi1btBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T15:56:53Z"
    mac: ENC[AES256_GCM,data:lXJf4Azhd0qfATDxtjg1y9Tx/OPaVwzzMrygNoFC6muTHsH41T1Dp7c0Pe9dg38OYeLYBAQYKsnSLbrW4g7/C9Wvffi0jfe5KCvs84SEsYttoaoDx1EI5KJPu0mwyL6o/68NLJMKbaj4jCfPFH09pQ3Dgpx0QfIZYE0eZIb1Nl0=,iv:19ah+/iE8lGb9UVUj1D3VkknuZxxL7H8MJiamElGgZo=,tag:dFiztU5yUDInjX5kVXPf/g==,type:str]
    version: 3.13.1
