apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-db
  namespace: paperless
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  bootstrap:
    initdb:
      database: paperless
      owner: deekline
      secret:
        name: paperless-db-credentials

  storage:
    size: 5Gi
    storageClass: longhorn
