apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-docs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.10.150
    path: /mnt/tank_small/paperless
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-docs
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: paperless-docs-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-nfs
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 10Gi
