apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: paperless-secrets
    namespace: paperless
spec:
    secretTemplates:
        - name: paperless-db-credentials
          stringData:
            username: ENC[AES256_GCM,data:4vo9RSeciYo=,iv:f35LAaGsKukrsL0232++D13V5GwClJG8iXGLtuVPdPg=,tag:Tcy7H9WGgu7NwUXXXY33ww==,type:str]
            password: ENC[AES256_GCM,data:8MXLaa5+5DdNxFHF70Lc,iv:35v2GZSWuRIJoK9LkVbKXN+bPRrg+cHHvaYtHgiJFTA=,tag:r4xJa6NjczQrisAwxwo/nw==,type:str]
        - name: paperless-secret-key
          stringData:
            secret-key: ENC[AES256_GCM,data:mB85gYl5ZGhsmIlZXtwlssnPBX+ltXKhZAD8HyfGn2kAv1mDZU4hBSfMhRX0zl+pY2a8WvaQNK6y5C4QbE6WcApd4w==,iv:ZTOGzf3BlHpsxesmCXumH/0sBPdrO7Sg4s0/eraA/IY=,tag:w9Og/xK6CXxOIiZcNDkv+w==,type:str]
        - name: dragonfly-secret
          stringData:
            password: ENC[AES256_GCM,data:8MXLaa5+5DdNxFHF70Lc,iv:35v2GZSWuRIJoK9LkVbKXN+bPRrg+cHHvaYtHgiJFTA=,tag:r4xJa6NjczQrisAwxwo/nw==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbkxOUkNvYkQ5QnZGTnZ4
            SVo3cTNnZmdpWWdXMXlqOGVDcVRGQ2hoMVhBClhyS3VFYUxBTEQyZHo0dmdVVlRk
            bWVLSXR0WFZYVG1Md2c2amQxVVpOS0EKLS0tIEJPbmtodlUzQW5FeGtzcGpNODJ0
            Z0dPSXhON0FtWW5SVi9vYWtJY2ZKRUkKXfz0qnXK3FrQ7T4dfzx70B9q82SaQxq6
            P3In8o5ACEgF/1Ru7VPdVBRo0GSpZC+bfHZEGRs3In3ZgnHr3/6zwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T16:31:33Z"
    mac: ENC[AES256_GCM,data:FfXfdG4mQz5/UjKIAF/bcMHhoMDnJNueLOBepqwG6jyJPoEN2B+W9IPYi+hFC+OZLQDKBtrPJH3m1zaG7ZSGYuus/kgrl4i4z9jXKYVaSx5FKDrPJd3XNi8etiEiGXL65ZWlKDtUQFeZv2iBbuoWodmtnOQryzgmkXqKPkuk8LM=,iv:iymGbQxmDQxu3u/qGbotZ/sSTD1UvCM3KAAyqfT8GGg=,tag:XAP8Qv+zLDvSmGYGd17aQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
