apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-db-backup-credentials
    namespace: immich
spec:
    secretTemplates:
        - name: immich-db-backup-credentials
          stringData:
            ACCESS_KEY_ID: ENC[AES256_GCM,data:1H91FVa11cW148MQpiv41fSglKY+jWCBYt8=,iv:uFlx9Utmq1yWC/W6A9dsS9V8P5wsqFEtf3FUBJF/siY=,tag:85DWDWBwBBF5Ej/SrqcRAg==,type:str]
            ACCESS_SECRET_KEY: ENC[AES256_GCM,data:xiPyAdsCiTWXf04JkQLWOGEAUJQRgpcfiN0YZT6iQvcXan1fe8DeWVNo3yMVjMYUR/Dd4PvI76/6k8SdEvA3hQ==,iv:DI5HxnKIzK8tXOsigRtW0U2tnNp+hFmbB28HWz5O5A4=,tag:4MZLFBtiM7O6jWlAo3JOhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Yi9zSVdtcFNFTHlUZjZu
            WnpYa3NYUUNnZ3d4Wi96SUh2QmxOTXNlbGw4CnBpMnkrOXdkQitjQnJpRnc2NFNO
            RWxaUnpVRmE0RGFjc3c3U0JNVU5mWW8KLS0tIHJQRVNaV05mWkNaOC9mOFFwWlRt
            Zk9xZ2tQanJZWExhTGVMUXBZOVU1NkEKobS/faTgoNO/6fetk7OBkHnsso+no+nu
            O+F+kCofhkiTnjKaIsoNxQ5CLbIanLMZ3/2HXsrdy+81j69bBCReKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T15:56:53Z"
    mac: ENC[AES256_GCM,data:Unyru64sSpG8c1IY8l5J15++nYByi4duyU+KsnVdAmuVoyylgTeINCm2gTViK67r/vxqil3Qqsm0otVgNyB21ZxoGsWvax0cGmax1BP3eU9oAyvuPE/fMBU4YeDwB/mOkQ2EeeAivC8BpW8rVC9g7+DbCgpU7NeGjena3qPDrus=,iv:uY/CZllXoJVCmYr0z3sWqOkLEL4q0wwRa/IFrUnwBZg=,tag:iQgPQLAhb24n6zNtZvDpdw==,type:str]
    version: 3.13.1
