apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - secrets.yaml
  - backup-credentials-secrets.yaml
  - backup-objectstore.yaml
  - postgres-cluster.yaml
  - scheduled-backup.yaml
  - ingressroute.yaml
  - pvc.yaml
  - network-policy.yaml
  - ml-network-policy.yaml
  - db-network-policy.yaml
