apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/gabe565/cloudnativepg-vecto-rs:16-vectors0.2.0

  postgresql:
    shared_preload_libraries:
      - vectors.so

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-credentials
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vectors CASCADE;
        - CREATE EXTENSION IF NOT EXISTS cube CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
        - GRANT USAGE ON SCHEMA vectors TO immich;
        - GRANT SELECT ON ALL TABLES IN SCHEMA vectors TO immich;
        - ALTER ROLE immich IN DATABASE immich SET search_path TO "$user", public, vectors;

  storage:
    size: 10Gi
    storageClass: nfs-db
