apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-secrets
    namespace: immich
spec:
    secretTemplates:
        - name: immich-db-credentials
          stringData:
            username: ENC[AES256_GCM,data:Nr0h64Yp,iv:2qyoKSWKQMmvbL1PFDXX4UT/2noDspGUTxvDzQVdOa4=,tag:64Rcl61nhCeSA1Eld9jbjg==,type:str]
            password: ENC[AES256_GCM,data:Yg2XJLNbWLXMaNgerT407EA=,iv:zIFNTMF1ERJIgZm5ts4quzMEvsTNAe8CuUaoJfwtqAk=,tag:VfklJhCs0+phYj7ZRLiyLg==,type:str]
        - name: dragonfly-secret
          stringData:
            password: ENC[AES256_GCM,data:RJrQpyvm8hcJtvs5GDJhSnG9cog=,iv:c2yfWikei/ZcwdE18U2KkeIy6vA9Xu4/7sNxpEskcjA=,tag:ktSOdLtg+iNDCoVOXyBbHg==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdHByeW1IMWxNL1ZtNGZF
            akQzdHpUZkExdU81V1JRYzZlUnRlTTRWdjBVCnpDTUdyUnd6RkhCNGZDMXRTK0NP
            dldEd0VPajZHV3h4L1dWREZLMWdWcFUKLS0tIEVKTHRxZXN4eEEvRDdMdkYwT2pl
            R1Q4Q1JFSTljTy9uUVcxdUNnSk9pNzgK1HYcxDh8xMApW5GHXpGnb9EUWfHeUf+I
            s5TBX+msOusJBJ0nL5iXnYHYvfei4mKBWuEgrlT5LvgvAGlbKDvpMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T15:22:39Z"
    mac: ENC[AES256_GCM,data:N9NtPZs1rFDl9PRja0LaMy5AHv2Y9lRl55+hNQNBxrC2am/Rv+MVwwc9kVCTGAxGEbsMb2pSbA0o4KvigL9hUa/mwn9yOXhvO3xKw219kplOCQd4+1d6kEvXp7gcBh5DCsClNAd5LK9sCy2Rq7OKwDvYd9db79Ga/a9Z1A9kS7U=,iv:bSCoiHkaGyw9defFjJXsEJ4bqFyNySyDqyHXgLLeXiQ=,tag:Q3C2qLINavNL8CDUMwiPJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
