apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-secrets
    namespace: immich
spec:
    secretTemplates:
        - name: immich-db-credentials
          stringData:
            username: ENC[AES256_GCM,data:Nr0h64Yp,iv:2qyoKSWKQMmvbL1PFDXX4UT/2noDspGUTxvDzQVdOa4=,tag:64Rcl61nhCeSA1Eld9jbjg==,type:str]
            password: ENC[AES256_GCM,data:Yg2XJLNbWLXMaNgerT407EA=,iv:zIFNTMF1ERJIgZm5ts4quzMEvsTNAe8CuUaoJfwtqAk=,tag:VfklJhCs0+phYj7ZRLiyLg==,type:str]
        - name: dragonfly-secret
          stringData:
            password: ENC[AES256_GCM,data:UVuxPqX7qTqoz9hqsS7W,iv:ya0WolQLlT2bO3Qe4Urc64H00/TH5ppAOAK7s1DFQ14=,tag:fzhDpDD79tojmJf6fni8Pw==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdHByeW1IMWxNL1ZtNGZF
            akQzdHpUZkExdU81V1JRYzZlUnRlTTRWdjBVCnpDTUdyUnd6RkhCNGZDMXRTK0NP
            dldEd0VPajZHV3h4L1dWREZLMWdWcFUKLS0tIEVKTHRxZXN4eEEvRDdMdkYwT2pl
            R1Q4Q1JFSTljTy9uUVcxdUNnSk9pNzgK1HYcxDh8xMApW5GHXpGnb9EUWfHeUf+I
            s5TBX+msOusJBJ0nL5iXnYHYvfei4mKBWuEgrlT5LvgvAGlbKDvpMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T16:31:17Z"
    mac: ENC[AES256_GCM,data:eHJMMAPk9owp/EM/qJp786+d9BimKv5d1q2nKMWqI1zIgFMOxVMj/MxFBQB3e8CE8f6CUZMZbJ7Ip5ot44wpHTfCYA0wk/HuQZip/Ue+3wmfdkmW80ZrJYFJ737vkCANxpNMIQondD3LTDpeoP0csTmBmCOkxk9ZcsM5NdvbqjU=,iv:iezgqQlhGzNqBgG15ptVos5tCZLgmgxGHhStV26FjPk=,tag:F+VcWe4OaD1fFncHv+XVcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
