apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: d-kline-org-wildcard
  namespace: traefik
spec:
  secretName: d-kline-org-tls
  issuerRef:
    name: cloudflare-letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "d-kline.org"
    - "*.d-kline.org"

---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  defaultCertificate:
    secretName: d-kline-org-tls
