apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: crowdsec-bouncer
    namespace: traefik
spec:
    secretTemplates:
        - name: crowdsec-bouncer-key
          stringData:
            key: ENC[AES256_GCM,data:OoyDFS4agBXG2yx04s0JrRqaJXt0BAbq2rwKErPwL+vaU6jdDZyhg244cA==,iv:gwnbA9W/pPe66H0WIxmgNtHHxk/Wggw3Q+SkmhPHGJc=,tag:3S6SmYcJfbLJGmf8gh0ReA==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d1NtaXFWZHVvTUswdzVJ
            aWhuSzJ2MXJPRDYrVDdpQ3BTeTdBRSsrM2lvCkFjRmc1TlpXM09EcGNvQ1RyQ0xt
            cjFlWFlLSWl1SlhVQjNITWpFUlBUNXMKLS0tIEhHeHdwcXRuOXlVMkF4ZlkwQkFT
            NFVuSXI2SWlNSDV4NDZyZnZnU1VFTXcKJUP3GbezC90YMYTLpx16TKZkxkSt+rTf
            kUtw0ZKy0NMgrL5YMfwy8/Do1+h13s5KeGgobmCzLfFw3wtw9uo2RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T09:45:04Z"
    mac: ENC[AES256_GCM,data:BXSHmrCEgsU/r0nlEkA8MT7xq7UhE/6l7Xgidq4mEphs38S6z+13SS7pBC72CBma6EE11+WEPKAEijQlmnH4aIKLAfqwxHd38LVw9+S/y5UBp7vtqv8KM4VnPtR/RKcGY4gO7T6mZoJln+m9br72GcYDH9HfpX4vDjQcLYLscs4=,iv:Uq2RW1Ax1rowE79q6BRkfjoQwc4qhJV5rRt4vFUca6o=,tag:5wP/ktu5fl90MfBwJP2sHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
