apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: crowdsec-bouncer
    namespace: traefik
spec:
    secretTemplates:
        - name: crowdsec-bouncer-key
          stringData:
            key: ENC[AES256_GCM,data:alsC9XDQVw8ccHY4nYmVxkbpHS97uTH0sDKrM2Zw2gRRVPJNfME7grzthA==,iv:rJv6D0PIA/c2P1xgWf/GYQP4jcBry1AhJgw88hL1jto=,tag:xMrAYmPcpF7aQDcxCwuFEg==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d1NtaXFWZHVvTUswdzVJ
            aWhuSzJ2MXJPRDYrVDdpQ3BTeTdBRSsrM2lvCkFjRmc1TlpXM09EcGNvQ1RyQ0xt
            cjFlWFlLSWl1SlhVQjNITWpFUlBUNXMKLS0tIEhHeHdwcXRuOXlVMkF4ZlkwQkFT
            NFVuSXI2SWlNSDV4NDZyZnZnU1VFTXcKJUP3GbezC90YMYTLpx16TKZkxkSt+rTf
            kUtw0ZKy0NMgrL5YMfwy8/Do1+h13s5KeGgobmCzLfFw3wtw9uo2RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:29:32Z"
    mac: ENC[AES256_GCM,data:CLZEOrl8b0NttINGSh7jrTvRIeX8AbgMpX2Nu4+GZipTk+Qa1vUN9ltHXJOziq1D8qnjy/rKxZJhSHeSaDsJRVxJKVCdb526GEqzE0bYyTJbekKLG9FYhERwMLHqVu0X1I9ugD1BmDyXNoJzEHuI0TkplhGO1p44jWPsP7i1KtI=,iv:3Qx91CL1tOxmGqvkqR4AvzFSDu3wWTXV3JVbNNb7m+s=,tag:dj6RyaxexIHWGzxG6YBi7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
