---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: ignorecert
  namespace: traefik
spec:
  serverName: "proxmox"
  insecureSkipVerify: true

---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: nasignore
  namespace: traefik
spec:
  serverName: "truenas"
  insecureSkipVerify: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynamic-config
  namespace: traefik
data:
  external-services.yml: |
    http:
      routers:
        proxmox:
          rule: "Host(`proxmox.d-kline.org`)"
          entryPoints:
            - websecure
          middlewares:
            - traefik-local-only@kubernetescrd
          service: proxmox
          tls: {}
        truenas:
          rule: "Host(`nas.d-kline.org`)"
          entryPoints:
            - websecure
          middlewares:
            - traefik-local-only@kubernetescrd
          service: truenas
          tls: {}
        opnsense:
          rule: "Host(`opnsense.d-kline.org`)"
          entryPoints:
            - websecure
          middlewares:
            - traefik-local-only@kubernetescrd
          service: opnsense
          tls: {}
        pihole:
          rule: "Host(`pihole.d-kline.org`)"
          entryPoints:
            - websecure
          middlewares:
            - traefik-local-only@kubernetescrd
          service: pihole
          tls: {}
        ha:
          rule: "Host(`ha.d-kline.org`)"
          entryPoints:
            - websecure
          middlewares:
            - traefik-local-only@kubernetescrd
          service: ha
          tls: {}
      services:
        proxmox:
          loadBalancer:
            passHostHeader: true
            serversTransport: "traefik-ignorecert@kubernetescrd"
            servers:
              - url: "https://10.0.10.2:8006"
        truenas:
          loadBalancer:
            passHostHeader: true
            serversTransport: "traefik-nasignore@kubernetescrd"
            servers:
              - url: "https://10.0.10.150:443"
        opnsense:
          loadBalancer:
            passHostHeader: true
            servers:
              - url: "http://10.0.10.1:80"
        pihole:
          loadBalancer:
            passHostHeader: true
            servers:
              - url: "http://10.0.10.10:80"
        ha:
          loadBalancer:
            passHostHeader: true
            servers:
              - url: "http://10.0.10.101:8123"
