apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - middlewares.yaml
  - api-service.yaml
  - dashboard.yaml
  - certificate.yaml
  - crowdsec-bouncer-secrets.yaml
  - external-services.yaml
