apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: speedtest-tracker-secrets
    namespace: speedtest-tracker
spec:
    secretTemplates:
        - name: speedtest-tracker-secrets
          stringData:
            APP_KEY: ENC[AES256_GCM,data:UeBf2NbwNootbQ0sI3DZ8+DZDVw+cx7yVhPXstxNLkultG9BrBmxLzIeE2v5FdtsCWr+,iv:o6nJ7cTC8p5KxILLM/KSb5m9kKv/zx8uw6gZCbb2pP0=,tag:0HxxKs/m269MchtqbqkmWg==,type:str]
        - name: speedtest-tracker-db-credentials
          stringData:
            username: ENC[AES256_GCM,data:3TyvhUW0eM4=,iv:73GojnIvIJ76mWkcztwdGwNyMqcCflv6Y+FPZp9jBz4=,tag:DhkmpxOVq8zBuPr6KIuFJw==,type:str]
            password: ENC[AES256_GCM,data:Vh/2Ylkg80i/ytqdvHoqeqPejH9ULA66fMdcVLBp53A=,iv:B9/eEc+J+XihgdeVY0vOEb8aPpRMAtyZV+DwBXE+Ato=,tag:em3+kYpQD9Qcm3kUmqaZHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbEVXNE1rS1NoRHNOZTkw
            R21TTFA4TjVFTEVRakJ0Si8rTmNEVlNiL1NzCklaZUtlZGJ1K0dCQ2hZa2NLZDFx
            cjRhOXpsQmE0YWc0bkZiR1BFazBSYzQKLS0tIExienhkeVg4NmZqeFJHZGYxY2Vj
            VVhPWUVBd1VjVCtVbXJYR2M4YnNsNjgKsZDLz+w+zUrcWnb9bbtd+Mb2K4Z1y45e
            OuIqoO+uXlX6m9pUOl+aq0CIMLLzCh5axzp8huOOHeUQ48YUsFhosg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T16:08:36Z"
    mac: ENC[AES256_GCM,data:u7iaEE+C22p8jnUknoIJyFB6j3tvB+PVVfgxbTzntD20SBjJOW27KCtJE3Jjw0SpyshFBSnOa57rwHKdgj3Ba84QdSiU7cJo85IfgUN8HXPkzzK5JhGqHzrfD6nhA3gcub3PGf/H0q3ddpCDW3Z4+ttHru29CSHaK2HC27LrD7Q=,iv:jPylCU4SI4v/PfFLGOt0s4iZqn3es2ZZDN/Q0OdrBwI=,tag:V9/58o2HbRrwUKQM0CbVNA==,type:str]
    version: 3.13.1
