apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: speedtest-tracker-secrets
    namespace: speedtest-tracker
spec:
    secretTemplates:
        - name: speedtest-tracker-secrets
          stringData:
            APP_KEY: ENC[AES256_GCM,data:iKpHxkBW0dQRZy6DtS7v+LRShH0BovyGbleWUd1teorq2Sp9lzH/WcP1LLo=,iv:jItCUEoa5itSmaYxJycqhUT/hHGyqI8DxQ27VUEAm8o=,tag:dGiwoOXjz42sMlrAfX5+ZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc0JmLzN5YTNOZFpTOUtN
            ZERobllHY2NTS0FCcmxVTnArRFZPcStuM2hZCmo5aHZRK1NkR0ppWTQrNW02bkZt
            dzJrc294emg0eVFMcnJKMXlNMmdLZDQKLS0tIDdGbEEvbGl2OTRkVzJCY1FsdHNB
            Mm81MkNPbXdwemZHZHJNOWhtelo1bTQKDmfz1CmRL/kc4ZA4g+pxYCt6rVkxNFK6
            lC0VLvWDS4s1ho00MTe4wWVzsLflN/TTAUyKLdMcApKuUZ3LSgZCnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T14:21:20Z"
    mac: ENC[AES256_GCM,data:BypObRYyCOw8Gzs5xYIOA8z+rKirQP8fwtU38x8IemJ3ZLVZDlt3V09eDiYHw55A03pvMqUiw/Y5D+YSf9MN985YMWW6ZtNqq/7GJWct9UaO9X9aEVIxBHDz9zsHI9vUX+D921HO9e0t8kn0Te5+ZnIOrS8X/OAB0fQkOlvLZdU=,iv:lF+XF8hHdFoGTiCYIBDqVZdEt9qjT1K+rClk6wL1AKM=,tag:JL7yf0I1ZVZ6x5MmiNSzyQ==,type:str]
    version: 3.13.1
