apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: crowdsec-bouncer
  namespace: traefik
spec:
  secretTemplates:
    - name: crowdsec-bouncer-key
      stringData:
        key: "DiF7ujhsDzHsfeiYEX+ajF4QqfhK3cPSO6BGlumCH3Y"
