apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: traefik-dashboard-auth
    namespace: traefik
spec:
    secretTemplates:
        - name: traefik-dashboard-auth
          type: Opaque
          stringData:
            users: ENC[AES256_GCM,data:gh8YyFIGRU1A66d3BKHB58XJxLeuwuzPJLK+9yNumUt2CRQH02YI36LICsbpuA==,iv:l54UqONuFL79Hhvs+vCShDRE5xGk9mKcaeIxIvSZB78=,tag:pjYblbjF0CQTOFKJZKsJhQ==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWFQ1YUh4NTlibW15a3Vl
            M2F0R3YyUWgvbENtMTBnTnZMWUZyN2JISWpFCldVS2lqT3lLYVNjc0J1dlVYeWVR
            cEd1dXp0Ykpmc0tlTHJ0cTJsdi8rOTQKLS0tIFdIYmlyZzVhUDRNSWhXd25pRU9h
            YnBrdkloS0tUZmk3Rjh4TlVra0VheEkKaNZNzcQfp/x9MYc7Ih4V09aqMbp5dM+B
            cvgRMQQ2wkMsIWMfhonhjainFP6y2ScL2qxNsao3HkK19GNER7mR8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:16:40Z"
    mac: ENC[AES256_GCM,data:lCqLcJ+7QKy8LiZBgkBAK4TvYnSiX1UbyBLahSWO0cgm0cXJUoAST4RsQcvMxJUphhgbXeApCKRVm0v2TYfeDCDTmmqG3HoegrlfQPT/isirBoGSC7UVHMmSePc3gGT7r4b+diP914ipwl4n/74rMulkUkfPCusvVolvodzMQco=,iv:RalLBVyK0d0Upa2dQBcdRfY66aHeaiFHb83Mpc7zZgQ=,tag:psNqotVoMu842qdgw3fLWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
