# Traefik dashboard basic auth
# Edit with: sops infra/k3s/traefik/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: traefik
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Tud6A2kJUZwdyCKFiXWHaw09yiLoyo3pwe69HkOr6YW49PNsxg7FNjSJ3rBHKr7Y,iv:uPEKJMqMAkV9tRFcH9HhwDI31NNkJyR3+iez6y3Fw/o=,tag:nfa/vHGCOsysavA46HJj/g==,type:comment]
    users: ENC[AES256_GCM,data:engq7NN3NW/zi5FAtciO2ir7RKtfo2A5oVtm32ElEiUFJ5NylrnhQGR13lQO2w==,iv:fGd/8l/lLSEhf+dF/spu89Y8wPsfet00Z6G8XhYPAoE=,tag:iJCC2GwQm/KHPBhQIHmdIw==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOWI3Rk1wSGZKelRVSjVw
            bGYrWk1aRFJZVTd5QVd6L0FrR2FOU0lmS1I0CkJZVkVodDFzcHNqTjgrclJqOUF5
            NU1CMzdUR3NnUCs2cXhoRDByMHFBL3MKLS0tIFY4dWkzdVkrSzVtejNpYytHRUFa
            R0hzYWRRek5KMC9xVDViN0Fib3d6cTAKfDOhZqt6md/LuwdEpJgV4O5/HslE/M2/
            0jM07Cz5EWO4aETtDiPD2rWHwAL1diUlHOXN2tIHn6AUxrfFm1b2rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T16:40:57Z"
    mac: ENC[AES256_GCM,data:Dh9ybRxApEUcP76dZh6sCtJ5ClAOMyfw/Jxr3aFcW0g2JLynUtclSNfF1FeFMj55OCartR2xCiuqsXxGq3eZxnp3JPtf8qwosSZTcQvtySPZukgyDwQ0ySjTz2LpuacfSmSPr9wLjZpF4bw4K8pY8hOS4M0WPoKOUE+H9P4PWhk=,iv:Se4/Ag7nyzcNPE1daBZIYm7G2tK6DH8p+OJ6zLb+Q88=,tag:8GZbjJJZ8UoKnPjt2HHU2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
