# Traefik dashboard basic auth
# Edit with: sops infra/k3s/traefik/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: traefik
    annotations:
        argocd.argoproj.io/sync-options: Skip=true
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Tud6A2kJUZwdyCKFiXWHaw09yiLoyo3pwe69HkOr6YW49PNsxg7FNjSJ3rBHKr7Y,iv:uPEKJMqMAkV9tRFcH9HhwDI31NNkJyR3+iez6y3Fw/o=,tag:nfa/vHGCOsysavA46HJj/g==,type:comment]
    users: ENC[AES256_GCM,data:engq7NN3NW/zi5FAtciO2ir7RKtfo2A5oVtm32ElEiUFJ5NylrnhQGR13lQO2w==,iv:fGd/8l/lLSEhf+dF/spu89Y8wPsfet00Z6G8XhYPAoE=,tag:iJCC2GwQm/KHPBhQIHmdIw==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOWI3Rk1wSGZKelRVSjVw
            bGYrWk1aRFJZVTd5QVd6L0FrR2FOU0lmS1I0CkJZVkVodDFzcHNqTjgrclJqOUF5
            NU1CMzdUR3NnUCs2cXhoRDByMHFBL3MKLS0tIFY4dWkzdVkrSzVtejNpYytHRUFa
            R0hzYWRRek5KMC9xVDViN0Fib3d6cTAKfDOhZqt6md/LuwdEpJgV4O5/HslE/M2/
            0jM07Cz5EWO4aETtDiPD2rWHwAL1diUlHOXN2tIHn6AUxrfFm1b2rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T18:51:12Z"
    mac: ENC[AES256_GCM,data:Fi0ZUp327/zbpVn1vj7ahmVFaPXf4AIwfYHSsoOQb2EcgqTZ+9IElIw+wi3wnygV4dKkPkccOEroAdadDQD0AEwC0JKLv1jlOR0Jw1D9NROFSQ+dC9aybJfj9Lra7dOyxyGpTl2XRKFoE21GpuRmwlkBWYGqMzPGTea4QRAt4bY=,iv:0AuWIUuzkeasub6ENdeLoVpVR/LZ1bBP6owBSZQH3BI=,tag:EiwkaadyI9MckLGOEE4PEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
