image:
  tag: "v3.6"

securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532

experimental:
  plugins:
    crowdsec:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.4.5"

ports:
  web:
    port: 8000
    exposedPort: 80
    protocol: TCP
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    port: 8443
    exposedPort: 443
    protocol: TCP
    transport:
      respondingTimeouts:
        readTimeout: 0s
        writeTimeout: 0s
        idleTimeout: 0s

service:
  type: LoadBalancer
  annotations:
    kube-vip.io/loadbalancerIPs: "10.0.10.9"
  spec:
    externalTrafficPolicy: Cluster
    loadBalancerIP: "10.0.10.9"

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

ingressRoute:
  dashboard:
    enabled: false

api:
  dashboard: true
  insecure: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

logs:
  general:
    level: INFO
  access:
    enabled: true
    format: json
    fields:
      general:
        defaultmode: keep
        names:
          ClientUsername: drop
      headers:
        defaultmode: keep

volumes:
  - name: crowdsec-bouncer-key
    mountPath: /etc/crowdsec
    type: secret

persistence:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi
