# Cloudflare credentials for cert-manager ClusterIssuer
# ClusterIssuer reads secrets from the cert-manager namespace
# Edit with: sops infra/k3s/cert-manager/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: traefik
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:Y2+Iz2jZwv5zmlsT7ZQU6eG4RkSODEhQqw==,iv:Q6nVYCmwF/DI7nyTYaopfGs+y3D8qpU9A9aUy0QofVo=,tag:fwO2ftI+fujxSO8X/y5BcQ==,type:str]
    api-token: ENC[AES256_GCM,data:H57Bg+6mdpEw4k4OT0SCTEE+BmOrc4deVJy6Fm/JWeWoAqyJzKJ+4g==,iv:qD98c/iJ/lPpg4PAwgfiwcuqB1EF1Tzt3GGkP5Qmjm8=,tag:jbLC78Wg9VZEtIeqf9aCXg==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OEp0MGVWK214aDF3SDla
            VHJPZ0NTcE1pU1BWR3VneVV6and5cWpmYWhRCnpUd3NlQ2VHS1BmMFFnMUg1UnZv
            M1ZUMDJ0N3puOWgrQklYQXprcVoxOUkKLS0tIHJGbU5qK2d4ZEVNL1pRUDVUTm1S
            TUZDRk5ManJKdGFrWUFpWE1CcWxEdjgKzZxsieZ1FgtzhEVX2fOqN0d5YaYTKhKG
            P/MqiAFfd5cX2K/HxG6xEn+O5LJ8kN9Hk5G4jnBJD4wxzrEgWAKWkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T16:46:21Z"
    mac: ENC[AES256_GCM,data:6lWA5q6K8YZSNSCGUwdm4/ifFsFv+BgY1NFQDXPWAjjSzKyJBlLN326aNeGeFV7BnLyRLb8gYqkiSjHbHqUiCoFgMWpIbtNnPrc7jjRPbnk1XYKAS/cj3UTuGNyQLSH6RfWdAzAQ424R+q1rxUKCUBG23NKd4JR//LXyOIR2Mhc=,iv:1W6eBA3LCEuifMsYOSdieW6RSWYHZkSC6tQ2qa7Fw04=,tag:rdk1ItBCvT3RwoiDuqGr4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
