# Cloudflare credentials for cert-manager ClusterIssuer
# ClusterIssuer reads secrets from the cert-manager namespace
# Edit with: sops infra/k3s/cert-manager/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: traefik
    annotations:
        argocd.argoproj.io/sync-options: Skip=true
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:Y2+Iz2jZwv5zmlsT7ZQU6eG4RkSODEhQqw==,iv:Q6nVYCmwF/DI7nyTYaopfGs+y3D8qpU9A9aUy0QofVo=,tag:fwO2ftI+fujxSO8X/y5BcQ==,type:str]
    api-token: ENC[AES256_GCM,data:H57Bg+6mdpEw4k4OT0SCTEE+BmOrc4deVJy6Fm/JWeWoAqyJzKJ+4g==,iv:qD98c/iJ/lPpg4PAwgfiwcuqB1EF1Tzt3GGkP5Qmjm8=,tag:jbLC78Wg9VZEtIeqf9aCXg==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OEp0MGVWK214aDF3SDla
            VHJPZ0NTcE1pU1BWR3VneVV6and5cWpmYWhRCnpUd3NlQ2VHS1BmMFFnMUg1UnZv
            M1ZUMDJ0N3puOWgrQklYQXprcVoxOUkKLS0tIHJGbU5qK2d4ZEVNL1pRUDVUTm1S
            TUZDRk5ManJKdGFrWUFpWE1CcWxEdjgKzZxsieZ1FgtzhEVX2fOqN0d5YaYTKhKG
            P/MqiAFfd5cX2K/HxG6xEn+O5LJ8kN9Hk5G4jnBJD4wxzrEgWAKWkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T18:50:43Z"
    mac: ENC[AES256_GCM,data:2LGKGUUP8fkt/Qfxa2rayeeUpSar7iDLDuGDBOG++e/y8juw5xM4QZzcWKzEGvT2HFgaG/vp7hols91Pr1OC61888B86peHJKmNRoUnq9mM/2TJ610izWzoeqnDwFVuPNKU78J06Y9aCApsGc+f+Hm6vy+a7Po/WiqWg9GxN6Z8=,iv:X3YJcdvxl7di7r5u3m1rm8xkVwgS4fz7oaOj6NojIT4=,tag:v/jXXXXTDm7eHRuMI8II1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
