apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-credentials-traefik
    namespace: traefik
spec:
    secretTemplates:
        - name: cloudflare-credentials
          type: Opaque
          stringData:
            email: ENC[AES256_GCM,data:b5FKq+T5900eyGK54pQHdYQzEEEZ,iv:XTLxQm4bi7nMm6iRUzJ9UVNk9zxWUmeMQvqlPoqQ8Do=,tag:tXOcoF8vA5Wml5vf/5llhQ==,type:str]
            api-token: ENC[AES256_GCM,data:JPH9mm3MWGhTolvOzc+8imRIR8tvsxUQNg==,iv:3wZx60UmhjH/FpFxY1gBpBhXfwRrla00Oz4Q9QarbGo=,tag:OTTyqWscwcD31vTq7w3/gg==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcFpBQVhnUFR3SjZZQkxB
            dlFSQ2VCLzdOVkdVeTAwUmd3K3lla2V4S3k0CmJTaWg4azl6VlBhL1hkZ0RobHZC
            SGpaV2M5VnpjNmd3cVBVWlhxMVhkMm8KLS0tIGVuR1pYZ2ErTkRvbDZLWlAzOENZ
            eVJDUGxwdjdiWk1CYmVadEdOL2dCczAKtxrXdrwAnVU2bVZapk0ooJLNdAD4BmWW
            0bz/cBEZXERzenxrCyMjV2osxCesmhFgX73e7/Nd175lhvAeZiLDEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:16:44Z"
    mac: ENC[AES256_GCM,data:/qtE3mNW6zY1TIygbWueg9pYcwFVtNJk0p0/l2Ybn99NVJaVCxGpgxWaSmCPyWEz5eIZn12waw2vCDi33XDH4GLn19NPOiLdNZEfpaeQYjT6cBZwy4v44XSs0XR+Lu3bB6HIjwa3otQ+90P9ZwMSLwOlZDQVvlDfOcVn3jsshzQ=,iv:jlOMHwXhe4wyMOwkSFSo2FXotGFXByg14claiUYHVfU=,tag:OwBSCXPs/KMZN0FdLBAdZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-credentials-cert-manager
    namespace: cert-manager
spec:
    secretTemplates:
        - name: cloudflare-credentials
          type: Opaque
          stringData:
            email: ENC[AES256_GCM,data:LSVvA3GL4AdCPktb+041plcyXF/i+if4FA==,iv:9FjUBbxgg0nq3Srk6fCMCx169KAUR6S71JGXABewClc=,tag:TF5d240QVQpvEbOAaCo/cw==,type:str]
            api-token: ENC[AES256_GCM,data:M5Gb/q8Ft+LsnUdCzWSsOfB+tuTA8++V1AvlkShvdHAMlQ/E5LDlQg==,iv:B706R3cpkr+ujtuKTi5lqU9w7ne9rL64HZyOhCDF92k=,tag:8/Y6eT70+s8nba/C8ToHwQ==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcFpBQVhnUFR3SjZZQkxB
            dlFSQ2VCLzdOVkdVeTAwUmd3K3lla2V4S3k0CmJTaWg4azl6VlBhL1hkZ0RobHZC
            SGpaV2M5VnpjNmd3cVBVWlhxMVhkMm8KLS0tIGVuR1pYZ2ErTkRvbDZLWlAzOENZ
            eVJDUGxwdjdiWk1CYmVadEdOL2dCczAKtxrXdrwAnVU2bVZapk0ooJLNdAD4BmWW
            0bz/cBEZXERzenxrCyMjV2osxCesmhFgX73e7/Nd175lhvAeZiLDEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:16:44Z"
    mac: ENC[AES256_GCM,data:/qtE3mNW6zY1TIygbWueg9pYcwFVtNJk0p0/l2Ybn99NVJaVCxGpgxWaSmCPyWEz5eIZn12waw2vCDi33XDH4GLn19NPOiLdNZEfpaeQYjT6cBZwy4v44XSs0XR+Lu3bB6HIjwa3otQ+90P9ZwMSLwOlZDQVvlDfOcVn3jsshzQ=,iv:jlOMHwXhe4wyMOwkSFSo2FXotGFXByg14claiUYHVfU=,tag:OwBSCXPs/KMZN0FdLBAdZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
