apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager-gotify-bridge-secrets
    namespace: monitoring
spec:
    secretTemplates:
        - name: alertmanager-gotify-bridge
          stringData:
            gotifyToken: ENC[AES256_GCM,data:lnx0LAe5ruRGySmmIwVd,iv:W7ivLrbwuk8bC9duXzb4boo7YvRr7Y3NM8Zmj21OoHY=,tag:JdEQLmevjPGQ6PltiefZQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdW1yUkg3R1A3V1JNNlE1
            SlNsSE9IMDNiZ2ZKV1o2Ym9yVS8yblF2YXk0CjAwNHl2VVF6QnFEbCtTL2Vpb1hj
            elhoalp1VG12TENSRWErZ3NjejIvWEkKLS0tIFNXZGwxSytDK0VDOXlTSWpqN2xW
            NWQzemZYTncxRWZ6cWtvRHNVNWd3bDgKbaCXKMQ0sQxZZzvQKO/jemiLy13Bt60t
            /NVbngWgTa2zSM8TEHRHzEgmLqHR4LfS/J6S3Leu+u52mMEEXtPn1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T14:19:53Z"
    mac: ENC[AES256_GCM,data:QaHfbuk6AjeG0srjgi/4cYHavAoO0ZoK99gSihsdCuGyHLpX7ln1+fsdFwhXCii7j40bYHrIBKArXhfz8cg+ZiJRQz4dmhgG9f11/028TNrHysYPJXU/v4bq4Wbc8YkC7q78Tj/8JxXotwgg+K0qvznjrCpf8MHQRaOMFcuHIG8=,iv:QepeQ5RufBKO1ZNhE/lbAvG514K7CRct4rl2bS2a4w8=,tag:yOvIVgwzBVrRwPbYF1LtuA==,type:str]
    version: 3.13.1
