apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager-gotify-bridge-secrets
    namespace: monitoring
spec:
    secretTemplates:
        - name: alertmanager-gotify-bridge
          stringData:
            gotifyToken: ENC[AES256_GCM,data:u+H6mALfq0ysq3Lt67ap,iv:ttoSpSfIOlmfc8T8tPGHwsY/wms6GKZ8L/qcBgJX+S0=,tag:gjVlwhMh1Dv5CVyY3mtXYA==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdW1yUkg3R1A3V1JNNlE1
            SlNsSE9IMDNiZ2ZKV1o2Ym9yVS8yblF2YXk0CjAwNHl2VVF6QnFEbCtTL2Vpb1hj
            elhoalp1VG12TENSRWErZ3NjejIvWEkKLS0tIFNXZGwxSytDK0VDOXlTSWpqN2xW
            NWQzemZYTncxRWZ6cWtvRHNVNWd3bDgKbaCXKMQ0sQxZZzvQKO/jemiLy13Bt60t
            /NVbngWgTa2zSM8TEHRHzEgmLqHR4LfS/J6S3Leu+u52mMEEXtPn1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T16:58:29Z"
    mac: ENC[AES256_GCM,data:r4mVmYqCU0iexroKZ53BtkUFa1Dok/WCIl6vRdtKG3lTGD4GPJWyuZ+RGINJMPm/yTGdu5C0i1WN9qgtqa47BNEdmD+w8MUtot5yB+7VC8+l7+56sKRUGjxQm9+Qwc1BpRqCoFPXV54JzbkBHVc0O1wPI1xJXLb8R7tz0M8wMGA=,iv:7vnte5gr3Ku/bAsXYlObNGZVNAD7P0V5RqxERo6puQY=,tag:dHRhQL4eS7DnvO2mBABUEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
