apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: crowdsec-secrets
    namespace: crowdsec
spec:
    secretTemplates:
        - name: crowdsec-secrets
          stringData:
            enrollKey: ENC[AES256_GCM,data:NUlbwnoLosmKKGAaAXjCrqgU2hTSNd98OjEURHEek2wjKkhYXFF8AL5dZQ==,iv:A/DTBtw/8CuhEqlxfFT4+bIvOSChsggz/9OH+sIeTvs=,tag:NTloPP+1YSy/FIw3nY0JcQ==,type:str]
            gotify-http.yaml: ENC[AES256_GCM,data:TZ2sxdaIDKpN8LwfeGfDAwNFPRIB8q/8Fz1y/Ks9aVXGTWFNEIegj2Qz8OO0/HG8LqwEMqbSiG5JsoRO+M2DXy6GKFNd1HnrF+/L/YN81UbiGXcroGEXz8hgrp83amuIY6mbXzSdW1UtKQdi66otdhrTAJBRQt0+djNNkQGJcfXx4dr+e+yljlGcffDkPobAJy5gapwMbKG00qdZCJmyzQwzCXM1q/IlAa1YkqsDVlL6CfBeseGJGHl35aVvr4m+4oZHMUwL/ReSldViPA3Uhfc521iSkwvqwqdnA05a94sj4gwdLV/+AnwsBszb2AqpgAp9iJ9G5TaBGYgb6M0+cSbz/LieLCmhD7HKkBh7Y6JGUT0p3Um970oNKRU1P951i1j7pWR2a9xtoEiXvrAWSqVDtgxzLSrGg+5HFPs5Abnv5ydxS8L18wpBd3a2cvInBuIZ7nlzxL4yeOvH,iv:j75NHLVu5N6CA5lNbDhn95OA4Pa4Xja6iRGydlv3qMw=,tag:5FjTkBI6ObeZhOOXDdaWzw==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWjFPNmp1SUN5dURNbzJG
            czNhZk5jcUE4aTFWMG96SktBMVBEN3U2WDI0CnE5akRwYXJZc1h5eWUvOWJGS2cv
            KzJEakpRY3lvSEVqbzVvRUZRbTRua28KLS0tIEhDVzN4M0FvMmJuR2t2UVBnc29h
            YmlkVVRyRGpYbHowSktxNmEvWWFwSXcK272Yiw4R0SoHueH+QCDnD9IlAiRnwdqv
            J/tpriaZm/sVzRBMLtaWC6ZfIDUNW7Zdc7wPjvNyG7PjOPQzveAEIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T12:08:46Z"
    mac: ENC[AES256_GCM,data:w0XMF/u/1XT2VnXdZ90QHhxqeCpMdPzUfWzRp4p0JjUFqRntWPhVI+Ilt7DpjzgdEgQuCHPGmXALFiXnIOfmTV/nLAUUR/XVC76tHb5m7zc4L0zoKSUMIDhwYEV9ElNm5M3H4cCEH2VJ92r8aZ5w3JcisXUc/Y85xE6vLoCvC/Y=,iv:4UdHxQ509qtWebJw9uc0GudKBI98klhSXizY3ivoxqo=,tag:b2i5s8a9VbyqAYRC+LVNVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
