apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: crowdsec-secrets
    namespace: crowdsec
spec:
    secretTemplates:
        - name: crowdsec-secrets
          stringData:
            enrollKey: ENC[AES256_GCM,data:NUlbwnoLosmKKGAaAXjCrqgU2hTSNd98OjEURHEek2wjKkhYXFF8AL5dZQ==,iv:A/DTBtw/8CuhEqlxfFT4+bIvOSChsggz/9OH+sIeTvs=,tag:NTloPP+1YSy/FIw3nY0JcQ==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWjFPNmp1SUN5dURNbzJG
            czNhZk5jcUE4aTFWMG96SktBMVBEN3U2WDI0CnE5akRwYXJZc1h5eWUvOWJGS2cv
            KzJEakpRY3lvSEVqbzVvRUZRbTRua28KLS0tIEhDVzN4M0FvMmJuR2t2UVBnc29h
            YmlkVVRyRGpYbHowSktxNmEvWWFwSXcK272Yiw4R0SoHueH+QCDnD9IlAiRnwdqv
            J/tpriaZm/sVzRBMLtaWC6ZfIDUNW7Zdc7wPjvNyG7PjOPQzveAEIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T12:27:21Z"
    mac: ENC[AES256_GCM,data:GEISeRyRtIExx9xcqUQtIXGzpsQQ3LAOdIixIBSMEc+HPdlduJ3cCkRUN53NxOA/LjdNGA8IGvpFVU3tqx9T8py8dbC9wWFtTnJ0CZCXgeJ8ojJoAdbBaYpcivLr25Q/PToHwNV3+tv0fwJRhXXz+f0WFc43MSOxwHMzgL0QWHA=,iv:qSAwRSoLwKBUIIiDWVkwQl1qvfEWUX56FWCzRApd/yQ=,tag:C+0SFtTcHMQTt+mWMdt4TQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
