container_runtime: containerd

lapi:
  secrets:
    existingSecret: crowdsec-secrets
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  persistentVolume:
    config:
      enabled: true
      existingClaim: crowdsec-config-nfs
    data:
      enabled: true
      existingClaim: crowdsec-db-nfs
  env:
    - name: ENROLL_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: enrollKey
          optional: true
    - name: REGISTRATION_TOKEN
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: registrationToken
  extraVolumes:
    - name: gotify-notifier
      secret:
        secretName: crowdsec-secrets
        items:
          - key: gotify-http.yaml
            path: gotify-http.yaml
  extraVolumeMounts:
    - name: gotify-notifier
      mountPath: /etc/crowdsec/notifications/gotify-http.yaml
      subPath: gotify-http.yaml
    - name: crowdsec-profiles-volume
      mountPath: /etc/crowdsec/profiles.yaml
      subPath: profiles.yaml

config:
  config.yaml.local: |
    api:
      client:
        unregister_on_exit: true
      server:
        auto_registration:
          enabled: true
          token: "${REGISTRATION_TOKEN}"
          allowed_ranges:
            - "127.0.0.1/32"
            - "10.0.0.0/8"
    db_config:
      flush:
        agents_autodelete:
          login_password: 6h

  profiles.yaml: |
    name: default_ip_remediation
    filters:
      - Alert.Remediation == true && Alert.GetScope() == "Ip"
    decisions:
      - type: ban
        duration: 4h
    notifications:
      - http_gotify
    on_success: break

agent:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/traefik crowdsecurity/linux"
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: agentUsername
    - name: REGISTRATION_TOKEN
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: registrationToken
    - name: CUSTOM_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik
      poll_without_inotify: true
