apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-secrets
    namespace: immich
spec:
    secretTemplates:
        - name: immich-db-credentials
          stringData:
            username: ENC[AES256_GCM,data:Nr0h64Yp,iv:2qyoKSWKQMmvbL1PFDXX4UT/2noDspGUTxvDzQVdOa4=,tag:64Rcl61nhCeSA1Eld9jbjg==,type:str]
            password: ENC[AES256_GCM,data:dv/mZGL5p5DHmS3SsPdWS1Q=,iv:hLo3jxUdN603aPwZyG+TGKFRJI+6O/m3k0g4n/0Uw6Q=,tag:tXI0FzcQxMpvxvaeF8qerQ==,type:str]
        - name: dragonfly-secret
          stringData:
            password: ENC[AES256_GCM,data:Yg2XJLNbWLXMaNgerT407EA=,iv:zIFNTMF1ERJIgZm5ts4quzMEvsTNAe8CuUaoJfwtqAk=,tag:VfklJhCs0+phYj7ZRLiyLg==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdHByeW1IMWxNL1ZtNGZF
            akQzdHpUZkExdU81V1JRYzZlUnRlTTRWdjBVCnpDTUdyUnd6RkhCNGZDMXRTK0NP
            dldEd0VPajZHV3h4L1dWREZLMWdWcFUKLS0tIEVKTHRxZXN4eEEvRDdMdkYwT2pl
            R1Q4Q1JFSTljTy9uUVcxdUNnSk9pNzgK1HYcxDh8xMApW5GHXpGnb9EUWfHeUf+I
            s5TBX+msOusJBJ0nL5iXnYHYvfei4mKBWuEgrlT5LvgvAGlbKDvpMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T13:27:23Z"
    mac: ENC[AES256_GCM,data:zGgoRG7onYhsLGgTLRMvbvPW9pweWbNqXbICUZfed5btydFcq2eEzgQgdYZ+el6eCiX9pvUzXSS2tl8dNu3QEmpz+qv3Kb0cpw5kIP0mGswxJiA9JmVhksriaXF1tsUjRjWd+Echt707zouUjyfsZZvf3KaFWkCqoRZ76it6syQ=,iv:kjrPaiDuOtsksaf82JBG8p3rmg260V3E199rsig4UIw=,tag:XZnx/CmY4Bk5SPGpJUfOHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
