apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: n8n-db-backup-credentials
    namespace: n8n
spec:
    secretTemplates:
        - name: n8n-db-backup-credentials
          stringData:
            ACCESS_KEY_ID: ENC[AES256_GCM,data:363WJeJpqD4mI6PwQEgvDrt9+L9U6GFiExQ=,iv:zCk0Xey4MvoxfaKWkloSfdf6S/Qemx6EpXSaNqfZ6K0=,tag:wfXPp5e2UA+BxgFhezsWtA==,type:str]
            ACCESS_SECRET_KEY: ENC[AES256_GCM,data:F+/hoIEGbc/N01tEuYgloPAjgDolSk05rd5WRWKgKT7MZNDBf/j3mrQij0KqDeNH7u1YZB2d5uJoBsdb5YC95g==,iv:CNX6yp32mGm8t0wbDN2ThR5ozU4XSgAenHgy8+7twSA=,tag:vz4T7SlP3t0WOI1RHzYSAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaitCNDZuQUt3TndqOERp
            OVk1QlZvNW1wTithcEszRldSTmxaK0tpYjMwClZrUC9aYjhpTkFxM2JHLzVER2M1
            RWpnelF6b2ZVWTNCUnlMdHJhT3FtL0UKLS0tIDhqK2s1b2xmN3lvWmhOZXBlb0Vt
            TFBkdlluOVJFTWdEZFlXcDcyV2FkcHMKvawlw6XT8C6yHH0Arq9XcI7IkDwsYWRs
            vIschwVI/alrCYyTHyeV+riZvHAkEXpNLC7eN3GT7kRn/yxaoIqj3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T16:00:09Z"
    mac: ENC[AES256_GCM,data:Oc1kQYF2GkDz2wdjO9j/yVZxcsE9aB0sQ7HTXwkG18eBDoeimdm1hi2muW73sFYMM27L/iHxA4MtUrEsA4FbG4D2WADyF55AFfYOLngt9z0GwndFQwAzwa5j+003fk8CPFgy0plqzmn2Nrj4AkGsi8BmGplGAtwM6ryEEAWkbBA=,iv:2GFyac1K1gvNpXdl86FK93NtNJR5xPQ72C3X4XJGAo8=,tag:s25khBJetD77Pmw98aoE6A==,type:str]
    version: 3.13.1
