apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: n8n-secrets
    namespace: n8n
spec:
    secretTemplates:
        - name: n8n-db-credentials
          stringData:
            username: ENC[AES256_GCM,data:x7gPfQ5/B6I=,iv:4xHgMaC8BVcoot/aRb3tV/7+ARER7ZkyNvKknudt654=,tag:HRNxDhlKrZFOBfwNNYVNOQ==,type:str]
            password: ENC[AES256_GCM,data:vKWwx6gyMt3zkAqev0E4eRoywEkcJ8ZbKumy8SZwP4Q=,iv:X7tSpVukGNL12zUudSKxFG5G2SM9EhH44q7XA01XF4o=,tag:AdykvVFIGKfEhy1qYrMYZw==,type:str]
        - name: n8n-encryption-key
          stringData:
            encryption-key: ENC[AES256_GCM,data:KyX5nvIhectWuxZok4nNIoqendM9YnyfLwg1hJ2zrUEIHx5Mwj+a/dRlrcAB2Dga+ZPQp6Aal25N6nr2fxdR5A==,iv:WJfvLOf6eOtdY57hGKvQb7LO0KGgYn+76hzwOg8b1Q8=,tag:svHvhKuxsDwBu1gZoAsbww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVUhCaXBkVUZyV2dpa0hx
            U3phV2pEWmNYSXRtTEw1cjA1ajJYbWI0aGd3ClFZZVBQZm9NVk5sQUFpYVF2eDRn
            RlI5VDJBemVTY242RzBFSDI5cUJreEUKLS0tIHh0TUd4QXNCZnZuclFNdGpaM2pF
            N3hvWmY5dFZkSExCZG9JbDgrSDhlRHcKvuc8RAu23rhLr35+BX6jSipDLcxxmMGy
            r94kjBVAH1yqVIx++8EGnfaOcaTWYaNpdjJnVvtoojhxZT9vHEyRPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T09:52:28Z"
    mac: ENC[AES256_GCM,data:vbPKY0E/QKEFGlRL8VHsYNAFN21Klz+JEZxumPqMmJdUqcTSQh6YTWvjCdZUSvFZ2/rblzdT7ynd39d8G7mLydfW2hxuuA8iCQJuY72Cs83eQ1hNjlggHfh+YWf0/7LZWRqrYkonBSSZYzdIMfiJKBKWCtOgIpMTQj/4zIvoAxU=,iv:Vy0J+kkKwrqb3pSmc0mdtktYfIFH9AwXQXpod/Hxj+0=,tag:VMa0G9hKPfCKMQOfM/KCZw==,type:str]
    version: 3.13.1
