apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
spec:
    secretTemplates:
        - name: grafana-admin-credentials
          stringData:
            admin-user: ENC[AES256_GCM,data:YOSTPdgnzNI=,iv:90ezUGuNz2Dj4u3z1tkMy2dZcGr1mTD2mjP+yF4rO5c=,tag:PNSVZwGr3ZMKmIaYkNouoA==,type:str]
            admin-password: ENC[AES256_GCM,data:hBC65mNnxb8mayFVZiw06qs=,iv:Na7B8sFxa+ELvUIUAvMw5O/nQQKdOaMoGukH8kFuSf4=,tag:4wMhGH8IKdEQNDQGrDFx2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VUZiangvVHV1S1l4WkNJ
            elphY09MTU5jVEdNSStPUExEc3pWaGlhUzFBCmZFU20vb20zVjdVUnFocFVTdUtz
            eE95TWdjbStCSmNDWFZ2K0prVHVrL0kKLS0tIE1pait5UDhsWVRVaDBhNEpkdWRa
            bjJQTTJEMWZyV0pCRkQwWEZ3QW5adU0K6ANOLFwQvgf++IMFM+DrIpLMvz9t4npE
            hSFJ30BHAE86y6GTISW0dHKOHfly92zUG7G7CGaMZbqXF/b5T5Fr9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T18:21:16Z"
    mac: ENC[AES256_GCM,data:qvnDO3rPxvh4RfPhNVkXHMT45S9zkvVF3EuAUBBshWWJpgbgUtJep5mDSw2ExZZ4+IYAw3FnGBQzaQv1cszPF1ULF+QUSV9NPZRSd0RGFAtatb8zWMM1rA3TXHOaLQhze3MlwMye8b4asbhLRtLILktxWYbTcbnT0x6ukEmfnLM=,iv:2ENYQtbFcr9bpFZEJD3MmJ3f25GWn+T4Ye346iqbCCM=,tag:klxfqwNJJCmVZgW4AoF03A==,type:str]
    version: 3.13.1
---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager-telegram
    namespace: monitoring
spec:
    secretTemplates:
        - name: alertmanager-telegram
          stringData:
            bot_token: ENC[AES256_GCM,data:BDWr6smN+vBBwEbZLPda2s1CBqXHsrAvCIV6YsMZJwecxgGD1A53a9pM7zXoLg==,iv:+393awjyIojI1YAfPm7b5ooWZwxCBEDxZnifB1UlFCE=,tag:oOzlxB3Ow10GF239LBBVBg==,type:str]
            chat_id: ENC[AES256_GCM,data:pX1y1T1NSoyT,iv:ZuY14MwZDH6ObkNJKLSootXwZLmSiBMH6N3M9zf1roU=,tag:p9jLbLAD2jtEwygWUToecg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VUZiangvVHV1S1l4WkNJ
            elphY09MTU5jVEdNSStPUExEc3pWaGlhUzFBCmZFU20vb20zVjdVUnFocFVTdUtz
            eE95TWdjbStCSmNDWFZ2K0prVHVrL0kKLS0tIE1pait5UDhsWVRVaDBhNEpkdWRa
            bjJQTTJEMWZyV0pCRkQwWEZ3QW5adU0K6ANOLFwQvgf++IMFM+DrIpLMvz9t4npE
            hSFJ30BHAE86y6GTISW0dHKOHfly92zUG7G7CGaMZbqXF/b5T5Fr9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T18:21:16Z"
    mac: ENC[AES256_GCM,data:qvnDO3rPxvh4RfPhNVkXHMT45S9zkvVF3EuAUBBshWWJpgbgUtJep5mDSw2ExZZ4+IYAw3FnGBQzaQv1cszPF1ULF+QUSV9NPZRSd0RGFAtatb8zWMM1rA3TXHOaLQhze3MlwMye8b4asbhLRtLILktxWYbTcbnT0x6ukEmfnLM=,iv:2ENYQtbFcr9bpFZEJD3MmJ3f25GWn+T4Ye346iqbCCM=,tag:klxfqwNJJCmVZgW4AoF03A==,type:str]
    version: 3.13.1
