apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git-source.yaml
  - root-kustomization.yaml
  - drawio.yaml
  - bentopdf.yaml
  - homarr.yaml
  - immich-power-tools.yaml
  - audiobookshelf.yaml
