apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader-values
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-infra
  path: ./k3s/reloader
  targetNamespace: flux-system
  prune: true
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 5m
  releaseName: reloader
  targetNamespace: reloader
  chart:
    spec:
      chart: reloader
      version: "2.2.14"
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: reloader-helm-values
      valuesKey: values.yaml
