apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@10.0.10.150:30009/deekline/homelab-infra.git
    targetRevision: deploy
    path: k3s/authelia
  destination:
    server: https://kubernetes.default.svc
    namespace: authelia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
