apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://crowdsecurity.github.io/helm-charts
      chart: crowdsec
      targetRevision: 0.22.1
      helm:
        valueFiles:
          - $values/k3s/crowdsec/values.yaml
    - repoURL: ssh://git@10.0.10.150:30009/deekline/homelab-infra.git
      targetRevision: deploy
      ref: values
    - repoURL: ssh://git@10.0.10.150:30009/deekline/homelab-infra.git
      targetRevision: deploy
      path: k3s/crowdsec/config
  destination:
    server: https://kubernetes.default.svc
    namespace: crowdsec
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: crowdsec-lapi-secrets
      namespace: crowdsec
      jsonPointers:
        - /data/csLapiSecret
        - /data/registrationToken
