apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: gitea-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: ssh://git@10.0.10.150:30009/deekline/homelab-infra.git
    targetRevision: deploy
    path: k3s/gitea-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
