apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: "1.11.1"
      helm:
        valueFiles:
          - $values/k3s/longhorn/values.yaml
    - repoURL: ssh://git@10.0.10.150:30009/deekline/homelab-infra.git
      targetRevision: deploy
      ref: values
    - repoURL: ssh://git@10.0.10.150:30009/deekline/homelab-infra.git
      targetRevision: deploy
      path: k3s/longhorn/config
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
