apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://isindir.github.io/sops-secrets-operator/
      chart: sops-secrets-operator
      targetRevision: ">=0.17.0"
      helm:
        valueFiles:
          - $values/k3s/sops-operator/values.yaml
    - repoURL: ssh://git@10.0.10.150:30009/deekline/homelab-infra.git
      targetRevision: deploy
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sops-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
