apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops-operator-values
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-infra
  path: ./k3s/sops-operator
  targetNamespace: flux-system
  prune: true
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sops-operator
  namespace: flux-system
spec:
  interval: 5m
  releaseName: sops-operator
  targetNamespace: sops-secrets-operator
  chart:
    spec:
      chart: sops-secrets-operator
      version: "0.28.0"
      sourceRef:
        kind: HelmRepository
        name: sops-secrets-operator
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: sops-operator-helm-values
      valuesKey: values.yaml
