apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.10.150
    path: /mnt/tank_small/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: media-library-pv
  storageClassName: ""
