apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: qbittorrent-secrets
    namespace: media
spec:
    secretTemplates:
        - name: qbittorrent-vpn-secrets
          stringData:
            WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:NdnxBHO5+pxmfbKHdNfcn2QhOD0OSr2izkxAWxji8e+D4+PCD8Hx7kJALuY=,iv:I5l1MwiCBKTJV8yMTGmeMMIX5OS6SmkCRXU7NiT9m2E=,tag:YcEW3aJMpsJQJUd7MUITmQ==,type:str]
            WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:/uqAYLEGIr7r57c=,iv:D2i5NPa+aobQIis/So/ArCqC4RNOLpVnHHbg4/g7qko=,tag:zPmRskPgyC3zzEKoILo70Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrU2JNUm5EeldFWUpTVEsv
            MjlZVGJ3SHNOSWhXQnVtSFIyUE9IZzg2YUdnCkhTUFBCeGlsOTMyMm5RR3NkL28z
            bmRubnNxeXRkMnlyZmw4V2w4MHFKbHMKLS0tIHdzVGg2U1lvVzBmWXljck1WcmpK
            ekF1bmN6THZlQUZDb0V3MmZ4amd3ZVkKEStjw2wl1Txm3GD9jvYyFJ/ugo3ZmWtT
            Yb0i8kfI1LMwrSQ4qhoRaBgg3xN+nwfe1y//d5ivWFkY9xMixXu26g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T14:34:12Z"
    mac: ENC[AES256_GCM,data:4mZk/eVs0ZVCgS3ifI586w8JSg/VTY6oJIEZ/95dClYTqIPE16Uep+sATzlYhIjLtktV7lxeCTAi57Zp8SY33QoCrOKI4AEqiiSIS6ROzVZMeAFFu4mqwNYWwvhX6NODKY6o9r15ML3KgTciitELEZ/taBhv4PBDj5fwr4x3ORs=,iv:1NFJFBdUSEiQ8K3N1QTKi7h5t3uqOCxYu/R/+wNO/3U=,tag:J+7f/A0EWz+Zai3isnN+Yw==,type:str]
    version: 3.13.1
