apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
spec:
    secretTemplates:
        - name: grafana-admin-credentials
          stringData:
            admin-user: ENC[AES256_GCM,data:YOSTPdgnzNI=,iv:90ezUGuNz2Dj4u3z1tkMy2dZcGr1mTD2mjP+yF4rO5c=,tag:PNSVZwGr3ZMKmIaYkNouoA==,type:str]
            admin-password: ENC[AES256_GCM,data:hBC65mNnxb8mayFVZiw06qs=,iv:Na7B8sFxa+ELvUIUAvMw5O/nQQKdOaMoGukH8kFuSf4=,tag:4wMhGH8IKdEQNDQGrDFx2Q==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VUZiangvVHV1S1l4WkNJ
            elphY09MTU5jVEdNSStPUExEc3pWaGlhUzFBCmZFU20vb20zVjdVUnFocFVTdUtz
            eE95TWdjbStCSmNDWFZ2K0prVHVrL0kKLS0tIE1pait5UDhsWVRVaDBhNEpkdWRa
            bjJQTTJEMWZyV0pCRkQwWEZ3QW5adU0K6ANOLFwQvgf++IMFM+DrIpLMvz9t4npE
            hSFJ30BHAE86y6GTISW0dHKOHfly92zUG7G7CGaMZbqXF/b5T5Fr9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T15:24:35Z"
    mac: ENC[AES256_GCM,data:W8RaAIRJyE2vrxV25JiQl6MgaoGhpqz7dZNHZN8HNS9B4qZ21phUnnqU8++hGi8WvEEhE/NDbNuxCWJ9mZ9epQwlMPdSvYNNSh7PDEI/Xe+MijXcCV1jmc+p8UScEqO92DrM/ABEPEvNkbLjzgdNvWczBHKwotb/4HzDafE+x7Q=,iv:ztkesWm5JR155tWkYOiS8yh3Jg1j3wkNOyDrf8QkyGw=,tag:d59+B9qWaZkbIBTL554RXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
