apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
spec:
    secretTemplates:
        - name: grafana-admin-credentials
          stringData:
            admin-user: ENC[AES256_GCM,data:YOSTPdgnzNI=,iv:90ezUGuNz2Dj4u3z1tkMy2dZcGr1mTD2mjP+yF4rO5c=,tag:PNSVZwGr3ZMKmIaYkNouoA==,type:str]
            admin-password: ENC[AES256_GCM,data:hBC65mNnxb8mayFVZiw06qs=,iv:Na7B8sFxa+ELvUIUAvMw5O/nQQKdOaMoGukH8kFuSf4=,tag:4wMhGH8IKdEQNDQGrDFx2Q==,type:str]
        - name: grafana-gotify-token
          stringData:
            GF_GOTIFY_TOKEN: ENC[AES256_GCM,data:hRYIisM+37c1Rd55OjQN,iv:8vp/XA4aZHBxxXTYx+oDFf/vmQ7a4uup4O5kcUYYYAI=,tag:ux+AZkiRsKSrF49hNSrmRA==,type:str]
sops:
    age:
        - recipient: age1vnjflcl0aeefw82f5klz764c4r5ddg9ad63y7vmu58dxmw026sms047q3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VUZiangvVHV1S1l4WkNJ
            elphY09MTU5jVEdNSStPUExEc3pWaGlhUzFBCmZFU20vb20zVjdVUnFocFVTdUtz
            eE95TWdjbStCSmNDWFZ2K0prVHVrL0kKLS0tIE1pait5UDhsWVRVaDBhNEpkdWRa
            bjJQTTJEMWZyV0pCRkQwWEZ3QW5adU0K6ANOLFwQvgf++IMFM+DrIpLMvz9t4npE
            hSFJ30BHAE86y6GTISW0dHKOHfly92zUG7G7CGaMZbqXF/b5T5Fr9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T16:23:11Z"
    mac: ENC[AES256_GCM,data:B2MoUjQfzjQ6IHCBooKvDcR4a3svE15SLUp+QbPbAv3UOhbZ14O+FpZbCYwz00BkAe5pwJq/YomCMEKrXsVWlNgXNVHvvMUnxJngHoe37xjblg9cV/rcH/HUbs+ZXy/yW/SxDBCHf46QlcacBnsFIO8hxnFbxICqTUlLJ7pswtc=,iv:yD3AlgaDPevI7DdL7KAFst4FLmQO1m2+MwTgNLD8Zz4=,tag:npPBdVkFpCWWCCLQBKyJaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
