apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-web-library-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.10.150
    path: /mnt/tank_small/calibre-web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-library
  namespace: calibre-web
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: calibre-web-library-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-web-ingest-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.10.150
    path: /mnt/tank_small/calibre-web-ingest
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-ingest
  namespace: calibre-web
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: calibre-web-ingest-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
  namespace: calibre-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 5Gi
