nfs:
  server: 10.0.10.150
  path: /mnt/SSD_SMALL/artifactory

storageClass:
  name: nfs-artifactory
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  archiveOnDelete: false

replicaCount: 1

podSecurityContext:
  runAsUser: 3003
  runAsGroup: 3005
