nfs:
  server: 10.0.10.150
  path: /mnt/SSD_SMALL/monitoring

storageClass:
  name: nfs-monitoring
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  archiveOnDelete: false

replicaCount: 1
