nfs:
  server: 10.0.10.150
  path: /mnt/SSD_SMALL/db

storageClass:
  name: nfs-db
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  archiveOnDelete: false
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
    - nodiratime
    - nconnect=8

replicaCount: 1

podSecurityContext:
  runAsUser: 3001
  runAsGroup: 3003
